### ISSUE TITLE
playwright: intergration

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#100]
Based on the original issue https://github.com/dequelabs/axe-puppeteer/issues/70 it looks like this would be a nice feature to have.

**Comment by stephenmathieson** [comment]
I am building E2E tests for the new axe app and am using playwright. I've had to hack my own integration together for this. It'd be great if we had an officially supported integration instead!

**Comment by leeuwe** [comment]
I'd like to upvote this. I'd just LOVE to move away from Selenium.

**Comment by leeuwe** [comment]
@michael-siek I've seen the PR and thanks for the work on it. Would you be able to give a rough estimate on when it will be available? This would be good to have as I need to make a decision how I'm going to implement axe-core, either by doing a bit more work to use axe-core, or wait for axe-core-npm/playwright to be available.
Thank you in advance.

**Comment by michael-siek** [comment]
Hey @leeuwe we are thinking that we will do a public release sometime in June.

**Comment by padmavemulapati** [comment]
Validated @axe-core/playwright Integration, following `ReadME` document.
Everything working as expected.
Steps followed for validation:
1. Installed `Playwright` (playwright@1.12.0)
2. Installed `@axe-core/playwright` (@axe-core/playwright@4.2.2-alpha.135)
3. created a test file 
``` test.js
const AxeBuilder = require('@axe-core/playwright').default;
const playwright = require('playwright');
const fs = require('fs');

(async () => {
  const browser = await playwright.chromium.launch();
  //const builder = new AxeBuilder({ page });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://qateam.dequecloud.com/attest/api/test.html');

  try {
    const results = await new AxeBuilder({ page }).analyze();
  
    fs.writeFile("./options.json", JSON.stringify(results, null,4),(err)=>
    {if(err){
        console.error(err);
        return;
        };
        console.log("File has been created");
    });
  } catch (e) {
    // do something with the error
  }
  await browser.close();
})();
```
got the expected results. and validated all the remaining APIs, `include` , `exclude`, `disableRules`, `withRules`, `withTags`, `options` etc.,

**Comment by michael-siek** [comment]
Hi @leeuwe, [`@axe-core/playwright`](https://www.npmjs.com/package/@axe-core/playwright) is now available but only as a canary release. We will do a stable release soon!

**Comment by leeuwe** [comment]
@michael-siek I've succesfully implemented @axe-core/playwright with my existing Playwright tests, feeding it the playwright Page object, and then feeding the returned object to axe-html-reporter from https://www.npmjs.com/package/axe-html-reporter. 
I'd say everything works splendid. Thanks for the work!
In the future, I'll be sharing my implementation with the world on LinkedIn.

**Comment by michael-siek** [comment]
That sounds awesome @leeuwe! Please feel free to share the post here or join the [axe Community slack channel](https://accessibility.deque.com/axe-community)
