### ISSUE TITLE
Verify Github Releases are being tagged correctly

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#1018]
Our Github releases are getting tagged to the commit right before the release. This means our versions are one behind and changelog entry does not exist for that release. The [maven release](https://search.maven.org/artifact/com.deque.html.axe-core/selenium) looks to be correct.

Example: 4.4.2 release [changelog](https://github.com/dequelabs/axe-core-maven-html/blob/v4.4.2/CHANGELOG.md) and [pom file](https://github.com/dequelabs/axe-core-maven-html/blob/v4.4.2/pom.xml)

**Comment by michael-siek** [comment]
verified
