### ISSUE TITLE
How to check the accessibility of an element with nth

### ISSUE THREAD

**Issue by jiz17043** [dequelabs/axe-core-npm#1021]
### Product

playwright

### Question

I have an element in the page using locator like this
page.locator('div.container').nth(1)
I wonder how could I check the accessibility of such element using include

**Comment by straker** [comment]
Thanks for the question. The `include` option is a CSS selector, so you'd have to craft a CSS selector that matches the element in question. If the `.container` elements are not siblings, you'll probably have to use a more specific selector to grab the one you want.

**Comment by padmavemulapati** [comment]
@michael-siek , Can you please suggest me any possible test using our test-fixtures
