### ISSUE TITLE
CLI: for Simplified Chinese and Taiwanese Mandarin are traslating in respective locale

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#1039]
### Product

cli

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Translation for locale should be in the respective language

#### Actual
Even we pass the `Taiwanese Mandarin` locale file - `axe.zh_TW.js` , translation is in General English only.
Same reported in [axe-core](https://github.com/dequelabs/axe-core/issues/4388)

https://github.com/dequelabs/axe-core-npm/assets/47409579/a177922c-7f75-4c79-bf88-acc45739cae3

#### How to Reproduce
1. create a directory and cd to that
2. npm init -y
3. npm i @axe-core/cli@rc
4. run the command `axe https://qateam.dequecloud.com/attest/api/test.html --axe-source .
/axe.zh_TW.js --save locale.json`

<img width="1043" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/bbbd316c-5380-42fa-84c1-7b618194e614">

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm_ |
|**Version** | _4.9.1-4cb64b0.0_ |
| **Selenium-webdriver-Version**           | _4.19.0_ |
| **OS-Details**      | _MACOS-Sonoma_14.4 and Windows 11 _ |
|**BrowserDetails**|_Chrome Version 123.0.6312.87   && Firefox 123.0.1_|

**Comment by michael-siek** [comment]
Closing it looks like the issue exist in axe-core https://github.com/dequelabs/axe-core/issues/4388#issuecomment-2034945694

**Comment by padmavemulapati** [comment]
Closing this as tracking in [axe-core ticket](https://github.com/dequelabs/axe-core/issues/4388)
