### ISSUE TITLE
"@axe-core/webdriverio": "^4.9.0" consumes a lot of memory resulting in javascript heap out of memory issue

### ISSUE THREAD

**Issue by Sameer-Dhole** [dequelabs/axe-core-npm#1044]
### Product

webdriverio

### Product Version

"@axe-core/webdriverio": "^4.9.0",

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Describe what you expected the product to do.

#### Actual
Describe what the product actually does.

#### How to Reproduce
Provide a code sample or link to a webpage that reproduces the issue. Without this, your issue may be closed without investigation.

#### Additional context
Any thing else we should know about the issue?

**Comment by Zidious** [comment]
Hey @Sameer-Dhole,

Are you able to provide more details on:

- How your test is written using the @axe-core/webdriverio package
- The URL being analysed
- If the URL is not public a reproducible snippet

Thanks

**Comment by Sameer-Dhole** [comment]
Hi @Zidious , we are using the below snippet . If you observe the memory of the node process the memory doubles after every few iterations

```
import { browser } from '@wdio/globals'
import AxeBuilder from '@axe-core/webdriverio'

describe('Accessibility Test', () => {
    it('should get the accessibility results from a page @sameer', async () => {
        for(var i = 0; i < 100 ; i++){
            // let builder = new AxeBuilder({ client: browser, noSandbox: true })
            await browser.url('https://testingbot.com')
            let result = await new AxeBuilder({ client: browser }).analyze()
            console.log('Acessibility Results:', result)
            result = null
        }
    })
})
```
Can you please help us here

**Comment by Sameer-Dhole** [comment]
@Zidious , did you find time to check this ?

**Comment by padmavemulapati** [comment]
Closing as there is no issue reproducing
