### ISSUE TITLE
Error Failed to open new tab - no browser is open when using Chrome 128 in headless mode

### ISSUE THREAD

**Issue by sarshad2024** [dequelabs/axe-core-npm#1116]
### Product

@axe-core/webdriverio

### Product Version

4.10.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Test is executed.

#### Actual
Test is not executed and there is the error "Failed to open new tab - no browser is open".

#### How to Reproduce
```
describe('Accessibility Test', () => {
  it('should get the accessibility results from a page', async () => {
      const builder = new AxeBuilder({ client: browser });

      await browser.url('https://testingbot.com');
      const result = await builder.analyze();
      console.log('Acessibility Results:', result);
  });
});
```
[
![error-no-browser-is-open-chrome-128](https://github.com/user-attachments/assets/a4c169f0-3ff8-4424-82c8-cc005734d490)
](url)

#### Additional context
Bug is present when using browser **Chrome version 128** in **headless mode**.

**Comment by michael-siek** [comment]
Hey @sarshad2024 I'll take a look and see what the issue could be

**Comment by sarshad2024** [comment]
@michael-siek Thanks!

**Comment by nayanrajDQ** [comment]
Hi @sarshad2024, 

I Tried to reproduce this issue, unfortunately i wasn't able to. 

Here is how the `browser` object looked like
```js
 browser = await remote({
      logLevel: 'error',
      capabilities: {
        browserName: 'chrome',
        browserVersion: '128.0.6613.113',
        'goog:chromeOptions': {
          args: ['disable-gpu', 'headless']
        }
   }
});
```
Let us know if i missing anything here or if you were able to reproduce it with the latest release, let us know the below things
- `webdriverio` version 
- `node` version

Thanks!

**Comment by sarshad2024** [comment]
Hello @nayanrajDQ,
I tested with WDIO latest version and my test case has been executed with success. The problem is no longer present. 
webdriverio v9
node v20.11.1
chrome v128.0.6613.113
Thanks!

**Comment by nayanrajDQ** [comment]
Closed as complete please reopen if relevant
