### ISSUE TITLE
[@axe-core/react] Uncaught TypeError: Cannot read property 'isConnected' of null

### ISSUE THREAD

**Issue by n370** [dequelabs/axe-core-npm#157]
I'm seeing this error being logged on the console.

https://github.com/dequelabs/axe-core-npm/blob/1f06cb67e2bbbf1922fd9d2e6bcee74f092cfa1c/packages/react/index.ts#L200

I'm wondering which situations `node` is expected to be `null` here.

**Comment by straker** [comment]
Sorry for the super late response. What error is being thrown exactly?

**Comment by n370** [comment]
Hey @straker thanks for getting back on this one. I'd have to find some time to try to reproduce this error again on my end but I think we fixed it by passing an empty object to the `axe` function fourth parameter like:

```
axe(React, ReactDOM, 1000, {});
```
You may be able to reproduce it by omitting that argument or passing `undefined`. I'll try to find some time to reproduce the error again and get back to you here.
