### ISSUE TITLE
CLI: save results with `--dir` weird behaviour

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#169]
Steps top reproduce:
If ran axe http://qateam.dequecloud.com/attest/api/test.html --dir ./axe-results/ 
results are outputting on console but failed to save in the specified directory with the below error message
(verified in the latest release-20201117 branch)
![image](https://user-images.githubusercontent.com/47409579/99666778-75358b80-2a91-11eb-9016-d0ac65cd83ed.png)

Note:
If we created directory manually in the working path before running the above command it is working fine.
@michael-siek , please le me know if this is expected behaviour.
Motivation:
It could be better , once on running the command it creates directory and save the results if there is no specific directory before .

Same observed in the axe-devtools-npm/cli. 
"Unable to save file!
Error: ENOENT: no such file or directory, open '/Users/dq_user/Documents/Newdevtools19Nov/axe-devtools-npm/packages/cli/save-results/axe-results-1605771564856.json'"

**Comment by padmavemulapati** [comment]
Verified in the latest axe-core-npm code base(dated 15th Jan 2021), now able to run command 
`axe http://qateam.dequecloud.com/attest/api/test.html --dir ./axe-results/`
and it is creating a specified directory when one does not exist.
![image](https://user-images.githubusercontent.com/47409579/104744505-f8621d80-5772-11eb-905a-baf75ec6a278.png)

**Comment by michael-siek** [comment]
Closing issue resolved
