### ISSUE TITLE
CLI: "Analyze the page using specific locale axe-source" test failing 

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#170]
Issue is not specific to axe-core-npm/cli, but test case is failing because axe-core is not able to generate axe.<locale>.js file , so as not able to provide test data to the test case.
Tracking the issue in: `https://github.com/dequelabs/axe-core/issues/2649`

**Comment by jeeyyy** [comment]
Closing this, as issue is tracked elsewhere.
