### ISSUE TITLE
React: Cannot read property 'runOnly' of undefined

### ISSUE THREAD

**Issue by mckelveygreg** [dequelabs/axe-core-npm#176]
Hello! Just updated to 4.1.0 and noticed new error in my console:
```
Uncaught (in promise) TypeError: Cannot read property 'runOnly' of undefined
    at Module.reactAxe [as default]
```
In the readme, it gives the example of skipping the configuration object to get the context object by passing `undefined`. 
```
// my old config
axe.default(React, ReactDOM, 1000, undefined, { include: [['#app']] });
```

The error disappeared when I passed an empty object instead, but I'm worried that I might be overriding some defaults? If not, I could open a PR to update the docs if you'd like.
```
// new docs change
const context = {
  include: [['#preview']]
};

axe(React, ReactDOM, 1000, {}, context);
```

**Comment by maneetgoyal** [comment]
Same issue. Needing to pass an empty object to make it work.

**Comment by PaulEbose** [comment]
I had this issue also. Found the bug here. 
https://github.com/dequelabs/axe-core-npm/blob/8d20dccda470e5f7ca8548d2d71e26ddc8387ad0/packages/react/index.ts#L358

The `conf` parameter does not have a default value, so the program is accessing `runOnly` from an _undefined_ value.

**Comment by padmavemulapati** [comment]
Verified with the latest `axe-core-npm` code - dated-28-12-2020, 
with the change in `runonly` option as -  `const runOnly = (conf || {})['runOnly'];` and declared a method for undefined `reactAxe(React, ReactDOM, 1000, {}, undefined);` , 
not seeing any `undefinied` type error 
![image](https://user-images.githubusercontent.com/47409579/103217520-c82b1a00-493e-11eb-874e-3ac9c0df014f.png)
