### ISSUE TITLE
New install: TypeError: conf is undefined

### ISSUE THREAD

**Issue by tarngerine** [dequelabs/axe-core-npm#180]
Playing with axe-core for react, copying code from the next.js example
<img width="862" alt="image" src="https://user-images.githubusercontent.com/1629901/101834657-4181da80-3b00-11eb-9cd8-aa431e7267ec.png">
Entire log: https://gist.github.com/tarngerine/a83b8e9dd5fe674366b61c2f0761f860

Happens on load

**Comment by 97carmine** [comment]
You have to set the [configuration](You have to set the configuration, although according to the documentation it is optional, without this it shows the error), although according to the documentation it is optional, without this it shows the error

If you don't see it clearly, I'll show you an example that I'm using:

```
import React, { hydrate } from "react-dom";
import { BrowserRouter } from "react-router-dom";
import App from "../common/components/app";

const config = { rules: [{ enabled: true }] };

if (process.env.NODE_ENV !== "production") {
	import("@axe-core/react").then((axe) => {
		axe.default(React, hydrate, 1000, config);
		hydrate(
			<BrowserRouter>
				<App />
			</BrowserRouter>,
			document.getElementById("root")
		);
	});
} else {
	hydrate(
		<BrowserRouter>
			<App />
		</BrowserRouter>,
		document.getElementById("root")
	);
}
```

**Comment by padmavemulapati** [comment]
As per the above  comments , not a bug and also there is a remediation.
