### ISSUE TITLE
Verify release script is failing

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core-npm#193]
See - https://app.circleci.com/pipelines/github/dequelabs/axe-core-npm/453/workflows/6a0f5884-bdcf-441d-a209-487bb1162b83/jobs/3263

It also seems like although the new version has been published as shown here:
![image](https://user-images.githubusercontent.com/20978252/106548555-d5ef3480-64d4-11eb-84a2-137d7290268a.png)

The actual page listing has not updated yet - https://www.npmjs.com/package/@axe-core/react

![image](https://user-images.githubusercontent.com/20978252/106548602-e99a9b00-64d4-11eb-9f1b-4914e3384943.png)

**Comment by michael-siek** [comment]
We _should_ remove the verify release script for react since there is no good way to test it via a monorepo https://github.com/dequelabs/axe-core-npm/issues/71

**Comment by michael-siek** [comment]
closing no docs required.
