### ISSUE TITLE
[@axe-core/webdriverjs] Typescript issue, missing type declaration file

### ISSUE THREAD

**Issue by J-VU** [dequelabs/axe-core-npm#195]
Type file _@types/axe-webdriverjs_ does not work with current webdriverjs

**Reproduce**
Create a typescript project using @axe-core/webdriverjs

**index.ts**
```
import AxeBuilder from '@axe-core/webdriverjs'
import WebDriver from 'selenium-webdriver'

const driver = new WebDriver.Builder().forBrowser('firefox').build()
driver.get('https://dequeuniversity.com/demo/mars/').then(function () {
  new AxeBuilder(driver).analyze(function (err, results) {
    if (err) {
      // Handle error somehow
    }
    console.log(results)
  })
})
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "lib": ["es2015", "es2017", "dom", "es2020"],
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es2017",
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "pretty": true,
    "strict": true,
    "sourceMap": true,
    "outDir": "./dist",
    "declaration": false,
    "skipLibCheck": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "baseUrl": "./",
    "paths": {
      "*": ["src/@types/*"]
    }
  },
  "include": ["src/**/*.ts"]
}
```

**Comment by michael-siek** [comment]
I tested this out and to add more context to this ticket it looks like `@types/axe-webdriverjs` doesn't support our 'new' scoped package `@axe-core/webdriverjs` so it produces this error
```console
implicitly has an 'any' type.
  Try `npm i --save-dev @types/axe-core__webdriverjs` if it exists or add a new declaration (.d.ts) file containing `declare module '@axe-core/webdriverjs';`ts(7016)
```

**Comment by pauchan** [comment]
Hi @michael-siek , thanks for the fix!
I'm hitting the same issue when trying to import `@types/axe-webdriverjs` in one of my projects. 
Would it be possible for you to consider releasing new version of the package with this fix in place?

**Comment by michael-siek** [comment]
Hi @pauchan we recently rewrote the entire [`@axe-core/webdriverjs`](https://github.com/dequelabs/axe-core-npm/pull/197) package in typescript so that we no longer have to rely on `@types/axe-webdriverjs`. You should be able to utilize the new package with `npm install @axe-core/webdriverjs@next` or the yarn equivalent

**Comment by pauchan** [comment]
Great to hear that!
I will try @axe-core/webdriverjs@next then. Thanks for the reply :)

**Comment by padmavemulapati** [comment]
Tried installed latest changes of axe-core/webdriverjs package globally as well local then executed the  script:

```js
const AxeBuilder = require('@axe-core/webdriverjs');
const WebDriver = require('selenium-webdriver');

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
(async () => {
  const driver = new WebDriver.Builder().forBrowser('chrome').build();
  await driver.get('http://qateam.dequecloud.com/attest/api/test.html');
  const results = await new AxeBuilder(driver, null, {
    noSandbox: true
  }).analyze();
  console.log(results);
  await driver.quit();
})();
```
got the expected results

**Comment by michael-siek** [comment]
Closing docs exist https://github.com/dequelabs/axe-core-npm/blob/develop/packages/webdriverjs/README.md
