### ISSUE TITLE
README at root level is not helpful

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core-npm#199]
Given this is OSS, it will be good to detail out all the packages that this mono-repo entails.
Something along the lines of the readme here - https://github.com/dequelabs/axe-core-gems

It is also good to have a contributing section.

**Comment by padmavemulapati** [comment]
Updated the README.md file with the relevant content page directions , where the ReadME files for all packages.
![image](https://user-images.githubusercontent.com/47409579/118499544-ab07b400-b744-11eb-999f-d2e5df7c225b.png)

**Comment by michael-siek** [comment]
Closing docs created.
