### ISSUE TITLE
Examples section was removed for webdriverjs package

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core-npm#200]
Currently published package of `@axe-core/webdriverjs` has examples section which will be super helpful if the links worked :)
> See https://www.npmjs.com/package/@axe-core/webdriverjs

The new re-write to TS seems to have lost the examples section, this should come back.
> See - https://github.com/dequelabs/axe-core-npm/tree/develop/packages/webdriverjs

**Comment by michael-siek** [comment]
Adding for context: https://github.com/dequelabs/axe-webdriverjs/blob/develop/README.md
