### ISSUE TITLE
Request to add license to NPM-hosted new axe-cli 

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core-npm#201]
We have an automated procurement system at my company. It requires ingested and hosted packages have a license associated with them. The latest, non-deprecated [NPM hosted axe-cli](https://www.npmjs.com/package/@axe-core/cli) has no license, as of version 4.1.1. 

Would it be possible to associate some sort of license? The standard MPL should allow us to ingest. Thanks!

**Comment by michael-siek** [comment]
Hi @kensgists `@axe-core/cli` package license is `MPL-2.0` https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli/package.json#L15

**Comment by kensgists** [comment]
Thanks @michael-siek. I'll keep an eye on the NPM site.
