### ISSUE TITLE
crypto doesn't exist in axe-core

### ISSUE THREAD

**Issue by AdrienLemaire** [dequelabs/axe-core-npm#210]
Versions:
- @axe-core/react 4.1.1
- webpack 5.25.1
- react 17.0.1

```console
✖ ｢wdm｣: ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in '/home/dori/Projects/Work/Project/v3/client/node_modules/axe-core'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/Compilation.js:1665:28
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:700:13
    at eval (eval at create (/home/dori/Projects/Work/Project/v3/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:271:22
    at eval (eval at create (/home/dori/Projects/Work/Project/v3/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:400:22
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:624:24
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:766:8
    at /home/dori/Projects/Work/Project/v3/client/node_modules/webpack/lib/NormalModuleFactory.js:886:5
✖ ｢wdm｣: resolve 'crypto' in '/home/dori/Projects/Work/Project/v3/client/node_modules/axe-core'
  Parsed request is a module
  using description file: /home/dori/Projects/Work/Project/v3/client/node_modules/axe-core/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/dori/Projects/Work/Project/v3/client/node_modules/axe-core/node_modules doesn't exist or is not a directory
      /home/dori/Projects/Work/Project/v3/client/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/dori/Projects/Work/Project/v3/client/node_modules
        single file module
          using description file: /home/dori/Projects/Work/Project/v3/client/package.json (relative path: ./node_modules/crypto)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto.mjs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto.tsx doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/dori/Projects/Work/Project/v3/client/node_modules/crypto.jsx doesn't exist
        /home/dori/Projects/Work/Project/v3/client/node_modules/crypto doesn't exist
      /home/dori/Projects/Work/Project/v3/node_modules doesn't exist or is not a directory
      /home/dori/Projects/Work/Project/node_modules doesn't exist or is not a directory
      /home/dori/Projects/Work/node_modules doesn't exist or is not a directory
      /home/dori/Projects/node_modules doesn't exist or is not a directory
      /home/dori/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

When reading `node_modules/axe-core/axe.js , I see

```js
    var uuid;
    var _rng;
    var _crypto = window.crypto || window.msCrypto;
    if (!_rng && _crypto && _crypto.getRandomValues) {
      var _rnds8 = new Uint8Array(16);
      _rng = function whatwgRNG() {
        _crypto.getRandomValues(_rnds8);
        return _rnds8;
      };
    }
    try {
      if (!_rng && require) {
        var nodeCrypto = require('crypto');
        _rng = function _rng() {
          return nodeCrypto.randomBytes(16);
        };
      }
    } catch (e) {}
```

But neither crypto nor uuid are part of the axe-core package.json dependencies.

For the time being, I'll add this to my webpack config:
```ts
{
  resolve: {
    fallback: {
      crypto: false,
    }
  }
}
```

**Comment by RyanWeissmanSopheon** [comment]
I am experiencing the same issue and using the same workaround. Not sure what functionality I am losing by setting the fallback to false.

**Comment by telb99** [comment]
Seeing browser error logs in Protractor based unit tests for Angular 11 project after switching from axe-webdriverjs to @axe-core/webdriverjs@4.1.1 & axe-core@4.1.3

WARNING https://localhost/polyfills.js 2348:8 "[WDS] Warnings while compiling."
WARNING https://localhost/polyfills.js 2357:10 "./node_modules/axe-core/axe.js 6275:19-26\nCritical dependency: require function is used in a way in which dependencies cannot be statically extracted"
WARNING https://localhost/polyfills.js 2357:10 "./node_modules/axe-core/axe.js\nModule not found: Error: Can't resolve 'crypto' in '.\\node_modules\\axe-core'"

Tried adding crypto as a dev dependency, made no difference
Tried downgrading to axe-core@4.1.2
Don't have control over webpack config so not sure how to get around this...

**Comment by michael-siek** [comment]
Hi, this issue should have been fixed in [axe-core@4.1.4](https://github.com/dequelabs/axe-core/releases/tag/v4.1.4) https://github.com/dequelabs/axe-core/pull/2843

**Comment by mcrawshaw** [comment]
@AdrienLemaire did the new version fix it for you? No luck for me...

**Comment by AdrienLemaire** [comment]
The [@axe-core/react](ttps://www.npmjs.com/package/@axe-core/react) package hasn't been updated yet, I haven't got a chance to test it.

**Comment by kelly-tock** [comment]
seeing this issue as part of storybook a11y addons as well.

**Comment by AdrienLemaire** [comment]
@michael-siek @WilcoFiers @straker  I noticed that although [npm](https://www.npmjs.com/package/@axe-core/react) lists `@axe-core/react` at version 4.1.1, [versions are still being pushed with an alpha suffix](https://www.npmjs.com/package/@axe-core/react)
Since 4.1.2-alpha.109 got released 9 hours ago, this should match [v4.2](https://github.com/dequelabs/axe-core/releases/tag/v4.2.0).

Unfortunately, with 4.1.2-alpha.109 , I'm still getting the error `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Comment by michael-siek** [comment]
Hi @AdrienLemaire, with axe-core@4.2 recently we are planning on doing an `@axe-core/*@4.2` release soon. All of the release with the suffix `-alpha.*` are canary releases which come from any commit that have been merged into the default branch of this repository.

**Comment by atanasster** [comment]
Hi, I am getting the error with 4.2, did you mean that it should be fixed?

```
WARNING in ../../node_modules/axe-core/axe.js 5299:25-42
Module not found: Error: Can't resolve 'crypto' in '.../node_modules/axe-core'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
```
reverting back to ` "axe-core": "4.1.2"` fixes it.

**Comment by padmavemulapati** [comment]
Verified as part of 4.2.0 release testing, not seeing issue.

**Comment by sethomas** [comment]
I am seeing the `Can't resolve 'crypto'` warning in `axe-core` 4.2.0 and 4.2.1 using the below setup:
```
"@cypress/react": "5.9.0",
"@cypress/webpack-dev-server": "1.3.1",
"cypress": "7.4.0",
"cypress-axe": "0.12.2",
```

When doing component testing via `cypress open-ct` I see the error.

**Comment by mkappelhof** [comment]
Got the issue too on version 4.2.1 with webpack on 5.37.0

Adding `fallback: { crypto: false }` to my Webpack config worked though

**Comment by seanforyou23** [comment]
This worked well for me with webpack@5.40.0 and @axe-core/react@4.2.2
```
  resolve: {
    fallback: {
      crypto: require.resolve('crypto-browserify'),
      buffer: require.resolve('buffer'),
      stream: require.resolve('stream-browserify')
    }
  }
```

**Comment by jackhair** [comment]
> Got the issue too on version 4.2.1 with webpack on 5.37.0
> 
> Adding `fallback: { crypto: false }` to my Webpack config worked though

What are the implications to setting the fallback to `false`, will it interfere with axe-tools?

**Comment by vasiliy-l** [comment]
> This worked well for me with webpack@5.40.0, @axe-core/react@4.2.2, and react@17.0.2
> 
> ```
>   resolve: {
>     fallback: {
>       crypto: require.resolve('crypto-browserify'),
>       buffer: require.resolve('buffer'),
>       stream: require.resolve('stream-browserify')
>     }
>   }
> ```

Thanks for solution!
Indeed, we can manually install and include missing Node.js modules as webpack 5 no longer polyfills them https://webpack.js.org/configuration/resolve/#resolvefallback

**Comment by michael-siek** [comment]
Closing no docs required
