### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by lucasbrunozup** [dequelabs/axe-core-npm#211]
Hello!

I am trying to use @axe-core/react in my project, but I am facing the following error:
![image](https://user-images.githubusercontent.com/69604366/111518368-c6e6dd80-8734-11eb-8a30-5f8bf3921906.png)

This is my implementation (index.tsx):
![image](https://user-images.githubusercontent.com/69604366/111518452-d8c88080-8734-11eb-8fd9-0dd3aa2c3f4a.png)

React Version: 16.13.1
@axe-core/react Version: 4.1.1

**Comment by Callenowy** [comment]
I'm facing the same issue.

```javascript
if (typeof window !== 'undefined' && process.env.NODE_ENV !== 'production') {
  (async () => {
    const { default: React } = await import('react');
    const { default: ReactDOM } = await import('react-dom');
    const { default: axe } = await import('@axe-core/react');

    axe(React, ReactDOM, 1000);
  })();
}
```

`react` 17.0.1
`react-dom` 17.0.1
`@axe-core/react` 4.1.1

**Comment by jefyelin** [comment]
I have the same issue in "@storybook/addon-a11y": "^6.1.21"

![image](https://user-images.githubusercontent.com/39713463/112058235-16644980-8b39-11eb-8436-3d48c1515f66.png)

**Comment by lucasbrunozup** [comment]
Can anyone help us?

**Comment by michael-siek** [comment]
Hi @Callenowy, @jefyelin, @lucasbrunozup, we currently have the fix in [axe-core](https://github.com/dequelabs/axe-core/pull/2843) once a release has been deployed in [axe-core](https://github.com/dequelabs/axe-core) we will update the dependencies in [axe-core-npm](https://github.com/dequelabs/axe-core-npm/).

**Comment by lucasbrunozup** [comment]
Okay, I'm waiting, thanks for the return.

**Comment by jefyelin** [comment]
Great! thanks for the return

**Comment by lucasbrunozup** [comment]
I noticed that there was an update to the ax-core, so when reinstalling ax-core/react, it didn't show any more errors. Thank you all!
