### ISSUE TITLE
Recursively find `<frame>` element

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#223]
Similar to this [PR](https://github.com/dequelabs/axe-core-npm/pull/209) we should find `<frame>` elements with the following integrations:
- [x] `@axe-core/webdriverio`
- [ ] `@axe-core/react`
- [ ] `@axe-core/puppeteer`
- [ ] `@axe-core/playwright`

**Comment by yokra9** [comment]
I'll contribute `@axe-core/webdriverio` by the end of may!

**Comment by Zidious** [comment]
Frames are deemed obsolete by W3C: https://www.w3.org/TR/html5-diff/#obsolete-elements 

Closing.
