### ISSUE TITLE
`@axe-core/*` v4.2 release 

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#233]
With [axe-core@4.2](https://github.com/dequelabs/axe-core/releases/tag/v4.2.0) release subsequent releases need to happen to all `axe-core-*` integrations. 

- [x] `@axe-core/cli`
- [x] `@axe-core/puppeteer`
- [x] `@axe-core/react`
- [x] `@axe-core/reporter-earl`
- [x] `@axe-core/webdriverio`
- [x] `@axe-core/webdriverjs`

**Comment by padmavemulapati** [comment]
QAed axe-core-npm4.2.0, and shared the report for the same across the team,
https://dequeqa.testrail.io/index.php?/reports/view/1113 - can find the report here

**Comment by michael-siek** [comment]
Closing this is complete
