### ISSUE TITLE
npm install - leading to error: Unexpected end of JSON input while parsing near '...  "_shasum" : "3b0992'

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#239]
Steps to reproduce:
1. Clone `axe-core-npm` latest code base
2.  When trying  to do `npm install` getting an error: Unexpected end of JSON input while parsing near '...  "_shasum" : "3b0992'

Product: axe-core-npm repo
Expectation: npm install should success

Actual: running with an issue saying "Unexpected end of JSON input while parsing near '...  "_shasum" : "3b0992' "

![image](https://user-images.githubusercontent.com/47409579/116847310-eca64400-ac07-11eb-8e5f-2dab89dd9e6d.png)

**Comment by michael-siek** [comment]
Closing unable to replicate
