### ISSUE TITLE
support puppeteer v9

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#241]
puppeteer is currently at v9 and the peerdependency for `@axe-core/puppeteer` is at v6 we should support the latest version of puppeteer.

**Comment by padmavemulapati** [comment]
When simply installed puppeteer - its installing puppeteer@5.5.0 , but installed puppeteer@latest - it installed
```PS C:\Users\DQ_Padmavathi\Desktop\npmcore\axe-core-npm\packages\puppeteer> npm install puppeteer@latest

> puppeteer@9.1.1 install C:\Users\DQ_Padmavathi\Desktop\npmcore\axe-core-npm\packages\puppeteer\node_modules\puppeteer
> node install.js

Downloading Chromium r869685 - 155.9 Mb [====================] 100% 0.0s
```
and example file executed and got the expected results with puppeteer@9.1.1

**Comment by michael-siek** [comment]
Closing no docs required.
