### ISSUE TITLE
React - feature proposal: Optionally turn off deduplication

### ISSUE THREAD

**Issue by charle692** [dequelabs/axe-core-npm#256]
Product: react

Expectation: 
Would love the ability to disable deduplication via a config option.

Actual: 
Currently the @axe-core/react stores reported issues in a cache (via key). If that issue has appeared before it will filter it out the logged issues.

Motivation: 
To give a little context on why I would like this feature, we currently invoke the axe tool when either of the following occur:
1. on initial page load
2. whenever a hot module replacement occurs
3. whenever the developer changes pages (via React router)

For case 1 everything is working perfectly. However, in case 2 and 3 I would love for all issues to be printed to the console. The reason for this is as follows. Imagine someone going through and fixing issues. They make changes to the code, go back to the browser and see if they fixed the issue. Hot module replacement kicks in and only replaces the changed module. (without refreshing the page). 

Since only "new" issues are printed to the console, the developer can't really determine if they resolved the issue. They now need to refresh the entire page to see if the issue has been resolved. For step 3, the same idea happens. Whenever the developer navigates to a different page (with React router) only "new" issues are printed to the console even if we're on an entirely different page. The benefit here is that you can treat each page change as an entire refresh, allowing you to easily determine which pages have issues and which do not.

From what I gather in the code, this is a simple addition that I can get in a PR tomorrow. If you take a look at [this function](https://github.com/dequelabs/axe-core-npm/blob/cbb795f1a92c419794a5f1f9645e28493d7c9bdb/packages/react/index.ts#L216), you will notice that it first checks to see if the issue's key exists in a cache object. If it does exist, the issue is filtered out. If it does not exist, it passes through the filter.

My proposal here is that we add a new configuration option next to `runOnly` called `deduplicate`. By default this will remain `true` as an opt-in feature/change. If this property is `false` then the filter function will always return `true` thus outputting all issues to console.

Let me know if this makes sense :).

<pre><code>
axe-core version: 4.1.1
@axe-core/react: 4.1.1

- Node version: 12.14.0
- Platform: all?
</code></pre>

**Comment by charle692** [comment]
If having an example of what I'm implementing helps understand more why I would like this, I've included a partial snipped of the implementation. 

```tsx
  let timeout: NodeJS.Timeout;
  const [isContentReloading, setIsContentReloading] = useState<boolean>(false);
  const { pathname } = useLocation();
  const [oldPathname, setOldPathname] = useState<string>(pathname);

  const loadAxe = () => {
    timeout = setTimeout(async () => {
      const axe = (await import("@axe-core/react")).default;
      axe(React, ReactDOM, 1000);
    }, 5000);
  };

  const statusHandler = (status: string) => {
    setIsContentReloading(status === "check");
  };

  useEffect(() => {
    if (isContentReloading || pathname !== oldPathname) {
      loadAxe();
      setOldPathname(pathname);
    }

    return () => clearTimeout(timeout);
  }, [isContentReloading, pathname]);

  useEffect(() => {
    loadAxe();

    if (module.hot) {
      module.hot.addStatusHandler(statusHandler);
    }

    return () => {
      clearTimeout(timeout);
      module.hot.removeStatusHandler(statusHandler);
    };
  }, []);
```

**Comment by Zidious** [comment]
Closing as merged.
