### ISSUE TITLE
feat(puppeteer): support puppeteer v10

### ISSUE THREAD

**Issue by Kieran-Reilly** [dequelabs/axe-core-npm#267]
Product: @axe-core/puppeteer

Expectation: Supports latest version of puppeteer (v10)

Actual: Peerdependency only supports v8

Motivation: We are running v10 within our use-case and would appreciate support for v10 to add automated accessibility tests.

**Comment by padmavemulapati** [comment]
Updated with puppeteer@10.0.0 and installed @axe-core/puppeteer@4.2.2-alpha.140, tested a sample page
'http://qateam.dequecloud.com/attest/api/test.html` , working as expected.

**Comment by michael-siek** [comment]
closing no docs required
