### ISSUE TITLE
'raw' reporter results undefined on @axe-core/puppeteer using axe-core >= 4.2.3

### ISSUE THREAD

**Issue by brocktaylor7** [dequelabs/axe-core-npm#323]
Product: puppeteer

Expectation: Return results when `raw` reporter is passed as a run option.

Actual: For all versions of axe-core >= 4.2.3, results return undefined when the `raw` reporter is passed as a run option.

Motivation:  I Need to be able to get the raw results from pages.

I have created a small sample app to reproduce the issue. There are 2 folders, one using axe-core 4.2.2, which was the last version in which it works as expected.  The other folder is using axe-core 4.3.2 and results return undefined when the raw reporter is passed as a run option.  Here is the link to the repo:

https://github.com/brocktaylor7/axe-puppeteer-raw-reporter-issue

<pre><code>
axe-core version: >= 4.2.3
@axe-core/puppeteer: 4.2.2

- Node version: 16.6.1
- Platform:  Windows
</code></pre>

**Comment by WilcoFiers** [comment]
Odd! Thanks for reporting. I'm working on axe-core/puppeteer today. I'll take a look.
