### ISSUE TITLE
axe-core/webdriverjs and webdriverio should support complex include / exclude

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core-npm#332]
This should be possible in webdriverjs / webdriverio

```js
new AxeBuilder()
  .include(['#myIframe', 'html'])
  .exclude(['#myIframe', 'main'])
```

This is possible in axe-core/puppeteer, but not in webdriverjs / webdriverio.

When we fix this, we should add better tests. Test coverage for include/exclude methods is kinda poor.

**Comment by padmavemulapati** [comment]
Validated during axe-core-npm 4.4.2 regression, on passing `include` and `exclude` options together with and without `iframes` , working as expected.
