### ISSUE TITLE
puppeteer: 4.3.3 audit

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#345]
* [x] Implements recursive runPartial
  * [x] injects and configures axe on each frame (exception: top-level iframe since axe might already be injected there from testing legacy code path)
  * [x] calls `axe.utils.getFrameContexts` on each frame
  * [x] runs `axe.runPartial` on each frame
  * [x] finds each iframe using `axe.utils.shadowSelect`
  * [x] calls function again with new iframe and context
  * [x] returns `null` if iframe errors for any reason and does not process children iframes
* [x] implements finishRun
  * [x] opens new tab and navigates to blank page (using `.goto` or `.navigate`, etc.)
  * [x] injects and configures axe
  * [x] calls `axe.finishRun` and passes results from all iframes
  * [x] closes blank page and returns driver context to original page
* [x] calls `axe.run` in legacy axe versions (where `axe.runPartial` is not defined)
* [x] implements all [fixture tests](https://github.com/dequelabs/axe-test-fixtures#tests)
  * [x] `analyze - throws if axe errors out on the top window`
  * [x] `analyze - throws when injecting a problematic source`
  * [x] `analyze - throws when a setup fails`
  * [x] `analyze - properly isolates the call to axe.finishRun`
  * [x] `analyze - returns correct results metadata`
  * [x] `frame tests - injects into nested iframes`
  * [x] `frame tests - injects into nested frameset`
  * [x] `frame tests - should work on shadow DOM iframes`
  * [x] `frame tests - reports erroring frames in frame-tested`
  * [x] `frame tests - returns the same results from runPartial as from legacy mode`
  * [x] `for versions without axe.runPartial - can run`
  * [x] `for versions without axe.runPartial - throws if the top level errors`
  * [x] `for versions without axe.runPartial -reports frame-tested`
  * [x] `with a custom ruleset - should find violations with customized helpUrl`
  * [x] `with a custom ruleset - configures in nested frames`
  * [x] `with a custom ruleset - works without runPartial`

**Comment by padmavemulapati** [comment]
Validated with `axe-core-4.3.3` , for implementing `finishRun()` we are seeing opening a new tab and navigates to blank page and all the tests with RunPartial are validated also legacy mode tests verified.
```
client.createWindow = () => {
            return { handle: null };
          };
```
`switchToWindow` - handling with by making sure drivers are up to date

`axe.runPartial()` and `axe.finishRun()` which opens a new window to finish running axe-core. 

All are working fine

**Comment by michael-siek** [comment]
closing no docs required
