### ISSUE TITLE
rewrite `@axe-core/cli` to ts

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#35]

**Comment by jeeyyy** [comment]
WIP - https://github.com/dequelabs/axe-core-npm/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by padmavemulapati** [comment]
Pulled the latest code for axe-core-npm and verified, its now running "**/**.test.ts" file instead "*.js" on cli
