### ISSUE TITLE
webdriverjs: 4.3.3 error handling audit

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#366]
- [x] finishRun error handling
  - [x] asserts `createWindow` or `window.open` returns a valid handle
  - [x] wraps `switchToWindow` in a try / catch
  - [x] wraps call to private `finishRun` in try / catch with a message that points to the error handling doc
- [x] Error handling doc

**Comment by michael-siek** [comment]
closing no docs required
