### ISSUE TITLE
all packages: restrict npm publish to just 'dist' directory

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#376]
Currently all files are published to npm, including those in the `src` directory. We should limit what we publish to be just the `dist` directory and needed root level files.

![image](https://user-images.githubusercontent.com/2433219/134046279-33e1c9a2-39b7-4edd-8f75-899ffc7d1246.png)

**Comment by padmavemulapati** [comment]
Earlier packages have `dist`, `src` and `test` folders
![image](https://user-images.githubusercontent.com/47409579/149897224-061250f1-59cd-4dfe-b874-0958531ea007.png)

Now its with only `dist`
![image](https://user-images.githubusercontent.com/47409579/149897276-923047d6-124d-4b60-91e4-20f4d43c46e8.png)

**Comment by Zidious** [comment]
Closing, no docs required.
