### ISSUE TITLE
Error: javascript error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by obivhankenobi** [dequelabs/axe-core-npm#385]
Product: A11y Test Automation

Expectation:  Proper json  results with "wcag2a", "wcag2aa" tags 

Actual:  it throws "Error: javascript error: Maximum call stack size exceeded"

Please see below for test cases: Please keep in mind, the issues below happened only on particular web pages among all web page URLs. Unfortunately, I can not share them with you due to security policies
1.
Scenario: Use only wcag2a tag 
Result: Max Call Stack Error
2.
Scenario: Use wcag2a and wcag2aa  tags 
Result: Max Call Stack Error
3.
Scenario: Use wcag2a and wcag2aa  tags and also enable legacy mode
Result: No issue
4.
Scenario: Use only wcag2aa tag 
Result: No issue

![axe-core max stack size error](https://user-images.githubusercontent.com/83100498/135713776-94b9b44d-4cf1-4f1a-ab4d-e28f3675aef5.png)

Motivation: << I would like to know why this issue only occurs with wcag2a tag >>

<pre><code>

async function executeTask(driver, url) {
  try {
    await driver.get(url);
    let result = await new AxeBuilder(driver, axeSource)
      .setLegacyMode()
      .withTags(["wcag2a", "wcag2aa"])
      .analyze();
    return Promise.resolve(result);
  } catch (err) {
    return Promise.reject(err);
  }
}

async function iterateThroughUrls(urls) {
  var driver = new WebDriver.Builder().forBrowser("chrome").build();

  for (const url of urls) {
    try {
      const result = await executeTask(driver, BASE_URL + url.slice(8));
      const results = {
        url: result.url,
        violations: result.violations,
      };
      const savedItem = await violationService.save(results);
    } catch (err) {
      console.log("Error during analyze ..");
      return console.error(err);
    }
  }
}

iterateThroughUrls(URLs);

axe-core version: 4.3.3
@axe-core/webdriverjs: 4.3.1

- Node version: v14.15.4  
- Platform: Windows  
</code></pre>

**Comment by Zidious** [comment]
Hey @obivhankenobi, 

Thank you for reporting this issue. Could you please confirm if this is still apparent on the latest version of WebDriverJS 4.3.2?

**Comment by obivhankenobi** [comment]
Hello @Zidious ,
Thank you for your answer, I switched to puppeteer and I haven't encountered any issues since
