### ISSUE TITLE
playwright: Chaining multiple .excludes() only excludes the last call

### ISSUE THREAD

**Issue by jen-w** [dequelabs/axe-core-npm#389]
Product: "@axe-core/playwright": "^4.3.1"

Expectation: 
The following code snippet creates a builder that will exclude both the `exclude1` and `exclude2` classes.
```
const builder = new AxeBuilder({ page })
            .exclude(".exclude1")
            .exclude(".exclude2");
```

Actual: It only excludes the "exclude2" class.

Motivation: I have multiple classes on my page that I want to exclude (not owned by my team or known logged issues).

Is there a workaround interim?

**Comment by padmavemulapati** [comment]
Validated as part of axe-core-npm release testing, chaining of scope scans are working fine
