### ISSUE TITLE
allow playwright to accept multi-array selectors 

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-npm#398]
Right now we have the ability to chain multiple includes/excludes:
```js
const builder = new AxeBuilder()
  .exclude('.exclude1')
  .exclude('.exclude2')
  
// or 
  
const builder = new AxeBuilder()
  .exclude(['.exclude1'])
  .exclude(['.exclude2'])
```
But not in the same array: 
```js
const builder = new AxeBuilder()
  .exclude(['.exclude1', '.exclude2'])
```
The above does not properly exclude classes `.exclude1` and `.exclude2`. 

Resource: [axe-core include/exclude](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#include-exclude-object)

edit: my apologies, the above include/exclude example is not correct. the correct layout for include/exclude for classes would look something like: 

```js
const builder = new AxeBuilder()
  .exclude([ ['.exclude1'], ['.exclude2'] ])
  ```

See bullet point 3 - Resource: [axe-core include/exclude](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#include-exclude-object)

Ref: https://github.com/dequelabs/axe-core-npm/pull/391

**Comment by Bracciata** [comment]
This should be fixed!

**Comment by Zidious** [comment]
See: https://github.com/dequelabs/axe-core-npm/pull/413#issuecomment-1007520245
