### ISSUE TITLE
Deprecate old repositories

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core-npm#4]
- [ ] Add note to `README.md`s pointing users here
- [ ] Run `npm deprecate` on the old project with a message telling users to move to `@axe-core/<package-name>`
- [ ] Archive the "old" repositories
- [ ] Make this repository "public"

**Comment by stephenmathieson** [comment]
@WilcoFiers @michael-siek I think we should do this, as folks are still opening issues/etc in the old repositories.

**Comment by jeeyyy** [comment]
@michael-siek to validate if all the issues from old repos need to be moved. To pair with @jeeyyy
