### ISSUE TITLE
support puppeteer v13

### ISSUE THREAD

**Issue by DaveTryon** [dequelabs/axe-core-npm#431]
Product: puppeteer

Expectation: Puppeteer is currently limited to v10 (see https://github.com/dequelabs/axe-core-npm/blob/develop/packages/puppeteer/package.json#L49). Current puppeteer version is 13.1.1. It would be ideal if current versions were supported.

Motivation: Being able to use current puppeteer features, keep transitive dependencies current

<pre><code>
axe-core version: X.Y.Z
@axe-core/[integration]: X.Y.Z

- Node version: XX  
- Platform:  
</code></pre>

**Comment by michael-siek** [comment]
Thank you for reporting! We will investigate this issue further and update you as soon as we can.

**Comment by Zidious** [comment]
Closing, no docs required
