### ISSUE TITLE
incorrect return type for `setLegacyMode` in webdriverio/js

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#444]
The return type for `setLegacyMode` is set to [`AxeBuilder` instead of `this`](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/webdriverio/src/index.ts#L144). This causes a typescript error when trying to chain the method.

Problem in both webdriverjs and webdriverio.

```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/test.ts(138,14): error TS2339: Property 'analyze' does not exist on type 'AxeBuilder'.
```

**Comment by padmavemulapati** [comment]
Validated while `axe-core-npm` QAing,
```
const axe = new AxeBuilder({ page }).setLegacyMode();
const results = await axe.analyze();
axe.setLegacyMode(true);
    //console.log(results);
```
working as expected. We are not calling `LegacyMode` with `this`, but using `AxeBuilder`
