### ISSUE TITLE
axe-cli fails with Chrome 98

### ISSUE THREAD

**Issue by acdha** [dequelabs/axe-core-npm#450]
Product: cli

Expectation: CLI runs

Actual: 

With a fresh install of Chrome, ChromeDriver, and `npm install @axe-core/cli -g` today:

```
cadams@Galatea ~> axe --show-errors http://localhost:8000
Running axe-core 4.4.1 in chrome-headless
Error: "session not created: This version of ChromeDriver only supports Chrome version 96\nCurrent browser version is 98.0.4758.80 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome" 
 $s SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 98.0.4758.80 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    at Object.throwDecodedError (/opt/homebrew/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/opt/homebrew/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:548:13)
    at Executor.execute (/opt/homebrew/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:474:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/
```

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: 4.3.2
@axe-core/[integration]: X.Y.Z

- Node version: v17.4.0
- Platform:  macOS 12.2.1
</code></pre>

**Comment by acdha** [comment]
It's not clear whether #448 will fix this

**Comment by Zidious** [comment]
Hey @acdha, 

Thank you for submitting this issue. 

You may need to enable the ChromeDriver in your firewall in macOS. If you locate the ChromeDriver executable, open it and you may need to enable the prompt that will appear under "Allow apps downloaded from"

<img width="780" alt="image" src="https://user-images.githubusercontent.com/41127686/153531302-05ca77d9-4146-4470-bd28-ce27ddefc3df.png">

Check the version: 

```sh
chromedriver --version
ChromeDriver 98.0.4758.80
``

**Comment by acdha** [comment]
Here's the chromedriver version:

```
cadams@Galatea ~> chromedriver --version
ChromeDriver 98.0.4758.80 (7f0488e8ba0d8e019187c6325a16c29d9b7f4989-refs/branch-heads/4758@{#972})
axe www.google.com --chromedriver-path (which chromedriver) --show-errors
Running axe-core 4.4.1 in chrome-headless
Error: "session not created: This version of ChromeDriver only supports Chrome version 96\nCurrent browser version is 98.0.4758.80 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome" 
 $s SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 96
```

**Comment by padmavemulapati** [comment]
@acdha try install cli with `@axe-core/cli@next` and do this chromedriver executable in terminal. It will resolve the problem

**Comment by Zidious** [comment]
Hey @acdha,

Apologies for the delay, we recently merged a PR to fix the ChromeDriver issue (to use `latest` for reference see https://github.com/dequelabs/axe-core-npm/pull/454). We will be doing a patch release shortly. However we have a canary release available, could you please try installing: `npm i @axe-core/cli@4.4.1-alpha.247 -g`. This build includes the fix: 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/41127686/154088186-62e4121d-c0e9-4479-91a9-c3367375d608.png">

**Comment by padmavemulapati** [comment]
Validated during latest patch release testing for (4.4.1-alpha.252)
It was always installed as a dependency, but now it's using `latest` instead of us pinning a chromedriver version. Example:
Prior to change:
if a user has Chrome V98, our package was pinned to V95 chromedriver, this would break CLI
New change:
If a user install CLI it will install latest chromedriver (say V99) their browser needs to be fully up to date
