### ISSUE TITLE
Playwright: How to configure options for a check?

### ISSUE THREAD

**Issue by eeter** [dequelabs/axe-core-npm#471]
Product: playwright

Expectation: I would like to configure options for `color-contrast` check in Axe analysis with Playwright.

Actual: Can't use `configure()` for AxeBuilder, and according to the documentation it isn't available in the API.

Motivation: With axe-core I have been able to configure `color-contrast` options with:

<pre><code>axe.configure({
  checks: [
    {
      id: 'color-contrast',
      options: { ... }
}]});
</code></pre>

Is there a way to configure check options with Playwright?

axe-core version: 4.4.1
@axe-core/playwright: 4.4.0

**Comment by eeter** [comment]
Hi, the need for using rule configuration would be to change ``boldValue`` of the color-contrast check (https://github.com/dequelabs/axe-core/blob/develop/lib/checks/color/color-contrast.json#L8). It's for a case where the specific font used on the page is such that it's seen as passing the accessibility criteria when ``boldValue`` is 600.

**Comment by michael-siek** [comment]
Closing as this is an enterprise feature

**Comment by somaalapati** [comment]
Nothing to QA here.
