### ISSUE TITLE
Error while testing on alert statement

### ISSUE THREAD

**Issue by Alex-Jongman** [dequelabs/axe-core-npm#485]
Product: cli

Expectation: Give a meaningful error message about the code under test

Actual: running the axe cli on a simple page containing a javascript alert statement only the error: ```An error occurred while testing this page.``` is shown, not that the error was caused by the alert statement.

Motivation: One now can think its an error of axe itself and not an error caused by the code to be tested.

<pre><code>
axe-core version: 4.4.1
@axe-core/[integration]: X.Y.Z

- Node version: v16.13.1
- Platform:  Windows
</code></pre>

**Comment by WilcoFiers** [comment]
Apologies for the delayed response. We're still exploring what we can do about this issue.

**Comment by michael-siek** [comment]
Closing added more error handling in CLI
Ref: https://github.com/dequelabs/axe-core-npm/pull/555, https://github.com/dequelabs/axe-core-npm/pull/421, https://github.com/dequelabs/axe-core-npm/pull/681, https://github.com/dequelabs/axe-core-npm/pull/680
