### ISSUE TITLE
Running axe-core 3.5.6 in chrome-headless Error: Error: Invalid URL: http:/ when tried running the axe cli command

### ISSUE THREAD

**Issue by KunalBhatia407** [dequelabs/axe-core-npm#501]
node version v18.0.0
npm version 8.7.0
Platform: Windows 10
Chrome driver downloaded version is chromedriver_100.0.4896.60.exe

Then installed axe CLI globally: npm install @axe-core/cli -g
Then, installed webdriver-manager and selenium webdriver
Note: I didnt set any system environmental path(Infact, dont know how to set for axe cli)
Further, tried running axe as per below command directly:
axe https://www.deque.com

Getting below error:
Error: Error: Invalid URL: http:/
    at getRequestOptions (C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\index.js:51:11)
    at new HttpClient (C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\index.js:90:21)
    at getStatus (C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\util.js:38:18)
    at checkServerStatus (C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\util.js:76:14)
    at C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\util.js:74:5
    at new Promise (<anonymous>)
    at Object.waitForServer (C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\http\util.js:57:10)
    at C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\remote\index.js:251:24
    at new Promise (<anonymous>)
    at C:\Users\Kunal\AppData\Roaming\npm\node_modules\@axe-core\cli\node_modules\selenium-webdriver\remote\index.js:246:20
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

Please let me know how to fix this issue.

**Comment by Zidious** [comment]
Hey @KunalBhatia407, 

It appears there may be a problem with Node18 and the CLI tool, we will need to investigate this once Node18 is in a stable LTS release. 

In the mean time, If you could use the current LTS version, Node16 ([NodeJS releases](https://nodejs.org/en/about/releases/)) and try again. 

Let mw know if you run into any other issues.

**Comment by KunalBhatia407** [comment]
Dear @Zidious 

After installing version nodev16, this issue has been solved in my system.

Thanks and cheers....

**Comment by Zidious** [comment]
:wave: 

After investing this it appears to be an issue with Node18 introduced a breaking change with `os.networkInterfaces()` which affected Selenium WebDriverJS (the driver used within axe-core-npm/cli). 

We will keep an eye on the next version update from Selenium WebDriverJS and update accordingly. 

For reference: 
https://github.com/SeleniumHQ/selenium/issues/10619
https://github.com/SeleniumHQ/selenium/pull/10611 - I tested this fix locally with our CLI and it does appear to fix the issue with Node18

\cc @jeffmagill -Node.js V18 issue: https://github.com/dequelabs/axe-core-npm/issues/493

**Comment by padmavemulapati** [comment]
with node version 16 everything working fine, as per the comments on node version 18, we will keep an eye on the further versions.
