### ISSUE TITLE
'lighthouse' is not recognized as an internal or external command, operable program or batch file when running the build in jenkins.

### ISSUE THREAD

**Issue by KunalBhatia407** [dequelabs/axe-core-npm#502]
C:\ProgramData\Jenkins\.jenkins\workspace\Project>lighthouse <URL> --disable-storage-reset --port 52224 --output-path=./report.json --output json 
'lighthouse' is not recognized as an internal or external command,
operable program or batch file.

C:\ProgramData\Jenkins\.jenkins\workspace\Project>exit 9009 
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

nodejs version 16
npm version 16
jenkins

Could you please see this issue?

**Comment by Zidious** [comment]
Hey @KunalBhatia407, 

Where is `lighthouse` this doesn't appear to be one of our tools / commands? Could you please provide a bit more context?

Thanks

**Comment by Zidious** [comment]
Closing due to no response. Please reopen if this is still an issue
