### ISSUE TITLE
More details about playwright doc

### ISSUE THREAD

**Issue by shinokada** [dequelabs/axe-core-npm#507]
I have a couple of questions regarding [Playwrright page](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/README.md) page.

1. Could you add how to run the code? Is it `node ./tests/mytest.ts` or `playwright ./tests/mytest` ?
2. Could you add how to test more than one page? I am not sure if I should test multiple pages, but if it is not recommended please state.
3. Could you add Svelte section? Since SvelteKit comes with Playwright, I'm not sure how to run axe-core-npm/playwright in Svelte.

**Comment by Zidious** [comment]
Hey @shinokada, 

Thanks for submitting your questions please see the below: 

1. If you're not using @axe-core/playwright within a test suite but rather a standalone file, then you can use: 
	
```js
node myfile.js
```
Or in TypeScript:
```ts
ts-node myfile.ts
```

2. It depends on how you have your test suite setup. if you're wanting to test multiple pages then you can have a test for each page. Example: 

I have used [mocha](https://www.npmjs.com/package/mocha) and [chai](https://www.npmjs.com/package/chai) for this.
```js
require("mocha");
const AxeBuilder = require("@axe-core/playwright").default;
const { assert } = require("chai");
const { chromium } = require("playwright");

describe("My test suite", () => {
  let page;
  let browser;

  beforeEach(async () => {
    browser = await chromium.launch();
    const context = await browser.newContext();
    page = await context.newPage();
  });

  afterEach(async () => {
    await browser.close();
  });

  describe("Accessibility testing: Deque.com", async () => {
    describe("landing page", () => {
      it("to have no violations", async () => {
        await page.goto("https://www.deque.com/");

        const axeResults = await new AxeBuilder({ page }).analyze();

        assert.lengthOf(axeResults.violations, 0);
      });
    });

    describe("company page", () => {
      it("to have no violations", async () => {
        await page.goto("https://www.deque.com/company/");

        const axeResults = await new AxeBuilder({ page }).analyze();

        assert.lengthOf(axeResults.violations, 0);
      });
    });
  });
});
```

3. I am unsure about SvelteKit - we will need to investigate this more and get back to you

Anymore questions, let me know. 

Gabe

**Comment by michael-siek** [comment]
Closing issue please reopen if needed
