### ISSUE TITLE
dependency upgrade for puppeteer to v14 for @axe-core/puppeteeer@4.4.2

### ISSUE THREAD

**Issue by codejunction** [dequelabs/axe-core-npm#525]
Product: puppeteer

Expectation: axe-core 4.4.2 should work on latest puppeteer v14

Actual: axe-core 4.4.2 has peer dependency uptil puppeteer@13

Motivation:  dependency upgrade for puppeteer to v14 for @axe-core/puppeteeer@4.4.2

<pre><code>
axe-core version: 4.4.2
@axe-core/puppeteer: 14.3.0

- Node version: 16.14.2  
- Platform:  Linux
- CI: Gitlab CI/CD

npm ERR! peer puppeteer@">=1.10.0 <= 13" from @axe-core/puppeteer@4.4.2
npm ERR! node_modules/@axe-core/puppeteer
npm ERR! @axe-core/puppeteer@"^4.4.2" from the root project

</code></pre>

**Comment by michael-siek** [comment]
Hey @codejunction I just created a PR to fix this issue please feel free to follow it https://github.com/dequelabs/axe-core-npm/pull/528 once it gets merged into develop you should be able to install `@axe-core/puppeteer@latest`

**Comment by michael-siek** [comment]
Hey @codejunction the PR was just fixed please feel free to run `npm install @axe-core/puppeteer@next` to use a canary version of `@axe-core/puppeteer` with updated `peerDependencies`

**Comment by padmavemulapati** [comment]
Validated against the `puppeteer@14.4.1` , with `@axe-core/puppeteer-4.4.3-alpha.290` and successfully getting the expected results. puppeteer version upgraded successfully
