### ISSUE TITLE
Support puppeteer version 15

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#534]
Puppeteer version 15 is out and we should update to support the update

**Comment by padmavemulapati** [comment]
Validated with the below list of dependencies:
```
  "dependencies": {
    "@axe-core/puppeteer": "^4.4.4-alpha.298",
    "axe-core": "^4.4.2",
    "puppeteer": "^15.0.1"
  } 
```
and working fine and seeing the expected results
