### ISSUE TITLE
Error: chrome.setDefaultService is not a function

### ISSUE THREAD

**Issue by renato-bohler** [dequelabs/axe-core-npm#538]
The following error started to happen on my project's pipeline today when running axe CLI:

![image](https://user-images.githubusercontent.com/25781956/177797800-c19db1c5-3b22-471f-8a12-bec433ce877b.png)

After a little bit of investigation, I've found out that the culprit is apparently version `4.3.1` of `selenium-webdriver` (published ~3 hours ago). The previous version (`4.3.0`) does contain the `setDefaultService` function:

![image](https://user-images.githubusercontent.com/25781956/177795221-dea81533-acb5-4900-8ce0-ec5fc7f6fca8.png)

But the new one (`4.3.1`) does not:

![image](https://user-images.githubusercontent.com/25781956/177795305-f823fbff-8935-43c1-bf45-5cc138db6f2d.png)

If that's not a bug on their side, this should be published as a breaking change (`5.0.0`), but in the meantime, using version `4.3.0 (exact)` is probably going to fix this issue on axe's side.

<pre><code>
axe-core version: 4.4.2
@axe-core/4.4.3

- Node version: v17.9.0
- Platform:  Linux
</code></pre>

**Comment by renato-bohler** [comment]
Just for future reference, I was able to work around this issue by adding this on the `Dockerfile` we're using, after installing `@axe-core/cli` globally.

```dockerfile
RUN cd $(npm list -g | head -n 1)/node_modules/@axe-core/cli && npm install selenium-webdriver@4.3.0 --save-exact
```

**Comment by MarkusJLechner** [comment]
I came across the same issue. The PR leading to this is https://github.com/SeleniumHQ/selenium/pull/10796

**Comment by padmavemulapati** [comment]
Validated with `axe-core-npm@4.4.4-alpha.299` version, selenium-webdriver@4.3.0 and chrome driver(104.0.0), not seeing any error.

**Comment by michael-siek** [comment]
Closing no docs required
