### ISSUE TITLE
@axe-core/cli failing to run tests in command line 

### ISSUE THREAD

**Issue by chekinto** [dequelabs/axe-core-npm#543]
When I run the following command to test a site 

```shell
axe https://www.deque.com
```

I get the following error message

<img width="589" alt="Screenshot 2022-07-26 at 08 45 48" src="https://user-images.githubusercontent.com/26909451/180952377-91812352-d488-4b27-bd37-b6819aebf906.png">

Product: CLI

Expectation: I expect the command to display any accessibility issues related to the url of the page we wish to test. 

Actual: I receive the following error message ``An error occurred while testing this page.`` (see image above for error message and details) 

Motivation: To use the axe-core/cli tool

<pre><code>
axe-core version: N/A
@axe-core/cli: 4.4.3

- Node version: v14.18.1
- Platform:  Mac

**Comment by Yosoyquemero** [comment]
same issue here! :(

**Comment by Zidious** [comment]
Hey all, 

Could you both run the below command and let me know what the stack trace outputs: 

```sh
axe https://www.deque.com/ --show-errors
```

**Comment by chekinto** [comment]
![Screenshot 2022-07-27 at 10 00 53](https://user-images.githubusercontent.com/26909451/181207414-d7d7d357-c8aa-4f96-8c00-5e278d561a96.png)

**Comment by Zidious** [comment]
Hey @chekinto, 

Please install our `@next` build, there was a breaking change that Selenium introduced in v4.3.1  removed this function `chrome.setDefaultService` reference: https://github.com/SeleniumHQ/selenium/pull/10796/files#diff-6c87d95a2288e92e15a6bb17710c763c01c2290e679beb26220858f3218b6a62L260.  

Please try the below: 
```sh
npm i -g @axe-core/cli@next
```

We will be doing a patch release soon.

**Comment by chekinto** [comment]
Thank you very much for your help and support

**Comment by padmavemulapati** [comment]
Validated with the latest version, `@axe-core/cli": "^4.4.4-alpha.299"` not seeing any error while testing the page.
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/47409579/184814993-19cc8701-d832-4210-8169-1d724f1af736.png">

**Comment by steinmb** [comment]
Confirm that `npm i -g @axe-core/cli@next` fixes the issue:

```
 npm i -g @axe-core/cli@next

changed 95 packages, and audited 96 packages in 4s

10 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities


axe https://www.deque.com/ --show-errors
Running axe-core 4.4.3 in chrome-headless

Testing https://www.deque.com/ ... please wait, this may take a minute.

  Violation of "landmark-no-duplicate-banner" with 1 occurrences!
    Ensures the document has at most one banner landmark. Correct invalid elements at:
     - #CybotCookiebotDialog
    For details, see: https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner

  Violation of "landmark-unique" with 2 occurrences!
    Landmarks should have a unique role or role/label/title (i.e. accessible name) combination. Correct invalid elements at:
     - #CybotCookiebotDialog
     - #main-navigation
    For details, see: https://dequeuniversity.com/rules/axe/4.4/landmark-unique

3 Accessibility issues detected.
Testing complete of 1 pages

Please note that only 20% to 50% of all accessibility issues can automatically be detected.
Manual testing is always required. For more information see:
https://dequeuniversity.com/curriculum/courses/testingmethods
```

**Comment by michael-siek** [comment]
Closing issue please feel free to reopen if relevant
