### ISSUE TITLE
Puppeteer: Branding name inconsistancy

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#546]
On help url:
Actual is appearing as
 "helpUrl": "https://dequeuniversity.com/rules/axe/4.4/accesskeys?application=axe-puppeteer"
        
But Expected is:
 "helpUrl": "https://dequeuniversity.com/rules/axe/4.4/accesskeys?application=puppeteer"

Motivation:        
To make sure all packages branding will follow a similar pattern of naming
(Attached screenshot)
<img width="902" alt="image" src="https://user-images.githubusercontent.com/47409579/184635795-5d9ca380-13ae-4cae-be16-d47ab9468302.png">

**Comment by michael-siek** [comment]
Closing no longer relevant

**Comment by padmavemulapati** [comment]
Re-opening as the application branding should expect as "puppeteer" instead "axe-puppeteer"
Latest execution of `@axe-core/puppeteer` result's `helpURL`:


![Image](https://github.com/dequelabs/axe-core-npm/assets/47409579/3d0b30f5-fd6f-43ca-829c-114b3957fc01)

and in the same build `@axe-core/webdriverio` showing as exepcted:


![Image](https://github.com/dequelabs/axe-core-npm/assets/47409579/68b997b0-60ee-411e-aa61-8cd04ef45e98)


Pelase update it for the sake of unique pattern

**Comment by dequejenn** [comment]
@padmavemulapati - we should make all have the prefix "axe-" so webdriverio becomes axe-webdriverio. Please approve this ticket (if there are no additional issues) and open new tickets that are needed to meet this naming convention with other platforms.
