### ISSUE TITLE
update to use axe-core version 4.4.3

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#568]
We should upgrade all packages to use axe-core version 4.4.3

**Comment by padmavemulapati** [comment]
Validated with the latest `axe-core-npm` canary build - `4.4.5-alpha.316` and all packages holding `axe-core_4.4.3`.
Validated through results as well axe-core_version test run


![Image](https://user-images.githubusercontent.com/47409579/192688006-1ad31e3c-fae9-4e5e-b5ac-d8f38199ea1a.png)
