### ISSUE TITLE
Investigate CLI / WebdriverJS `chrome.setDefaultService`

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-npm#580]
We should Investigate if we need `chrome.setDefaultService()` used within CLI as we are blocked from updating Selenium WebdriverJS from 4.3

```js
// Pinned to selenium-webdriver@4.3.0
// https://github.com/SeleniumHQ/selenium/pull/10796/files#diff-6c87d95a2288e92e15a6bb17710c763c01c2290e679beb26220858f3218b6a62L260
chrome.setDefaultService(service);
```

source: https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli/src/lib/webdriver.ts#L16-L19

**Comment by Zidious** [comment]
We can utilize a similar solve: https://github.com/dequelabs/axe-core/pull/3735


> const service = new chrome.ServiceBuilder(chromedriver.path).build();

source: [axe-core PR 3735](https://github.com/dequelabs/axe-core/pull/3735/files#diff-b397dbc1a4e2a30d61fa57e182c8868779fc44d43a6fbe817ff3a7197e9446c3R128)

**Comment by padmavemulapati** [comment]
Valdiated `@axe-core/webdriverjs` - selenium version to  `  "selenium-webdriver": "^4.8.1",` with this working as expected
