### ISSUE TITLE
What happened to react version 4.4.5?

### ISSUE THREAD

**Issue by ptmkenny** [dequelabs/axe-core-npm#595]
Today, I just checked for new packages with `npm outdated` and got this output:

```
Package                  Current   Wanted   Latest  Location                              Depended by
@axe-core/react            4.4.5    4.3.3    4.3.3  node_modules/@axe-core/react          ionic
```

According to github, the latest release is 4.4.5, but now npm is showing [4.3 as the latest version](https://www.npmjs.com/package/@axe-core/react).

It seems like somehow yesterday [4.3.3 got published](https://github.com/dequelabs/axe-core-npm/releases)?

**Comment by Zidious** [comment]
Hey @ptmkenny, 

This was as mistake and is now corrected - https://www.npmjs.com/package/@axe-core/react `latest` is now `4.5.0`

**Comment by Zidious** [comment]
Closing - feel free to reopen
