### ISSUE TITLE
Support axe core shadow dom selector

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#615]
Ref: https://github.com/dequelabs/axe-core/pull/3798

With axe core having the ability to select shadow dom in the 4.6 release the axe core npm drivers that support the include/exclude methods should also support this. We would need to make sure to also update the selector types within each method to the new types provided by axe-core 

```ts
import type { Selector, SelectorList } from 'axe-core';

class AxeBuilder {

 constructor() { }
 
 public async include(selector: Selector | SelectorList) { }
 
 public async exclude(selector: Selector | SelectorList) { }
  
}
```

**Comment by straker** [comment]
We can now use `SerialFrameSelector` for the include / exclude `selector` type.

**Comment by padmavemulapati** [comment]
Validated with the latest `axe-core-npm_4.5.3-alpha.357` on implementing `shadow-dom` fixture.
With the shadow-dom test file - 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Nested Frames</title>
  </head>
  <body>
    <h1>This page has shadow DOM!</h1>
    <button id="button">Outside</button>
    <div id="shadow-root-1">
      <button id="light-button">Light</button>
    </div>
    <div id="shadow-root-2"></div>

    <script>
      const shadowRoot1 = document
        .querySelector('#shadow-root-1')
        .attachShadow({ mode: 'open' });
      shadowRoot1.innerHTML = `
        <button id="shadow-button-1">Shadow</button>
        <slot />
      `;

      const shadowRoot2 = document
        .querySelector('#shadow-root-2')
        .attachShadow({ mode: 'open' });
      shadowRoot2.innerHTML = `
        <button id="shadow-button-2">Shadow</button>
        <slot />
      `;
    </script>
  </body>
</html>
```
for all four packages of npm supporting shadow-dom selector.
Here are the expected outcome
For axe-core-webdriverio: selector includes
```
const builder = new AxeBuilder({ client });
  const results = await builder.include('#shadow-root-2').analyze();
```



![Image](https://user-images.githubusercontent.com/47409579/209043514-45902fd3-dcd8-45f9-a598-e11998617796.png)

for axe-core-webdriverjs: selector includes:
```
new AxeBuilder(driver).include([['#shadow-root-1', '#shadow-button-1']])
    .withRules(['button-name'])
    .analyze(function (err, results) {
    if (err) {
      // Handle error somehow
    }
```


![Image](https://user-images.githubusercontent.com/47409579/209043874-47164284-8fb7-4dce-9d21-68043da8426e.png)

for axe-core-puppeteer: selector includes:
```
const results = await new AxePuppeteer(page).include('#shadow-root-2').analyze();
```


![Image](https://user-images.githubusercontent.com/47409579/209044081-3ca365f8-ccc7-4135-b7d9-5b0885ea5e9f.png)


for axe-core-playwright: selector includes:
```
const results = await new AxeBuilder({ page })
    .include([['#shadow-root-1', '#shadow-button-1']])
    .withRules(['button-name'])
    .analyze()
```


![Image](https://user-images.githubusercontent.com/47409579/209044221-145fc6b5-5f72-4314-9ae1-74d98eeada00.png)


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Test URL**                | _http://qateam.dequecloud.com/attest/api/shadow-dom.html_ |
| **axe-core-npmVersion**           | _4.5.3-alpha.357_ |
| **OS**                              | _Windows 10 and MAC-OS-11.6.8_ |
| **Tested Browsers**       | _Chrome Version 108.0.5359.124 _ |
| **Dependencies Vesions** | _Puppeteer_19.4.1, Playwright_1.29.0, webdriverio_7.26.0_ |
