### ISSUE TITLE
Feature request: built-in failure assertion method

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dequelabs/axe-core-npm#647]
**Product**: playwright

**Expectation**: It'd be nice to have a method provided by `@axe-core/playwright` that throws an informative error to fail a test if no aXe issues are found. How about using [`expect.extends`](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend) to provide a built in expectation?

```js
// Proposal: setup

import { expect } from '@playwright/test';
import { matchers } from "@axe-core/playwright";

expect.extend(matchers);
```

```js
// Proposal: usage in tests

const results = await new AxeBuilder({ page }).analyze();

expect(results).toPassAxe();
```

**Actual**: There doesn't seem to be a way to throw an informative error in `@axe-core/playwright`? Examples such as https://github.com/dequelabs/axe-core-npm/blob/420c68543010c72627d0cfb6469a4ba769cff071/packages/playwright/example.js just show console.logging the results:

```js
const results = await new AxeBuilder({ page }).analyze();
console.log(results);
```

**Motivation**: It'd be nice to not have to write this code in every project that uses `@axe-core/playwright`:

* It's more effort to have to keep rewriting the same code
* Different projects might format things differently
* It's easy to mistake the current `.analyze()` API as being something you can call on its own & expect test failures from _(I made this mistake!)_

Here's a code snippet I've started using:

```js
const results = await new AxeBuilder({ page }).analyze();

expect(
  results.violations.length,
  [
    "Accessibility violations found. Run aXe to view more details:",
    ...results.violations.map(
      (violation) =>
        `- [${violation.id}] ${violation.help} (${violation.impact})`
    ),
  ].join("\n")
).toBe(0);
```

Example output:

```plaintext
    Error: Accessibility violations found. Run aXe to view more details:
    - [html-has-lang] <html> element must have a lang attribute (serious)
    - [label] Form elements must have labels (critical)
    - [landmark-one-main] Document should have one main landmark (moderate)
    - [region] All page content should be contained by landmarks (moderate)

    Expected: 0
    Received: 4
```

<pre><code>
axe-core version: 4.6.2
@axe-core/playwright: 4.5.2

- Node version: n/a
- Platform: n/a
</code></pre>

I'd be happy to contribute this as a PR if you'd like! ❤️

**Comment by straker** [comment]
Thanks for the suggestion. Unfortunately this is out-of-scope for this project. Something like this would be geared specifically towards a specific testing framework (in this case, playwright test), but our projects can be used in any testing framework. We have no intentions of releasing assertion methods for each testing framework.

**Comment by JoshuaKGoldberg** [comment]
Got it, thanks @straker! I'll try to find time to release this as a standalone package & link back to it here.
