### ISSUE TITLE
CLI: `--save`/`--dir` doesn't work when `--exit` is specified

### ISSUE THREAD

**Issue by jorupp** [dequelabs/axe-core-npm#656]
Product: cli

Expectation: Should be able to use `--exit` and `--save`/`--dir` on the same call.

Actual: When both are specified, `--exit` works, but `--save`/`--dir` seems to be ignored.

Motivation: As part of my CI process, I'd like to have axe fail my build, but still get the detailed JSON file to include in reports.

<pre><code>
axe-core version: 4.6.1
@axe-core/cli: 4.6.0

- Node version: 18.12.1
- Platform:  Windows
</code></pre>

This doesn't write `file.json`:
```
axe https://google.com --save file.json --exit
```

This writes `file.json`:
```
axe https://google.com --save file.json
```

**Comment by Zidious** [comment]
Hey @jorupp,

Thanks for reporting this issue. 

Apologies for the delay - I have confirmed this issue is still apparent on our latest version.

We will prioritise a fix for this, in the mean time feel free to open a PR to resolve this too.

**Comment by padmavemulapati** [comment]
Validated with the latest canary build (axe-core/cli_4.7.4-alpha.406) .
With the earlier, after scanning a page with the options (--save/dir along with --exit) page is scanning but results are not getting saved into specific file/folder. (see the screenshot)



![Image](https://github.com/dequelabs/axe-core-npm/assets/47409579/826cfab3-49ce-466a-801f-58b055e87c3e)






Not in the latest canary it got fixed and page is scanned successfully along with both the options and the results are getting saved properly in specifed file/folder.


![Image](https://github.com/dequelabs/axe-core-npm/assets/47409579/eca5a59e-bd26-49fe-88db-b66580e8ddfa)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/cli_ |
|**Version** | _4.7.4-alpha.406_ |
| **Type**           | _Package_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 114.0.5735.110 (Official Build) (64-bit)_|

**Comment by padmavemulapati** [comment]
Verified as part RC-4.8.0 - working as expected:


![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/3dcb393e-82c5-48d3-8619-ffa090e56b58)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm/cli_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
