### ISSUE TITLE
Next.js build crashing in example

### ISSUE THREAD

**Issue by pdavies88** [dequelabs/axe-core-npm#661]
Product: react -> next.js example

Expectation: Using `npm i` and `npm dev` a local server should build 

Actual: The local server crashes due to some errors in the code

Motivation: There are some quick fixes that will allow the build to be stable again

Suggested Fixes list:
1. Move `static` folder inside of a `public` folder - https://nextjs.org/docs/messages/static-dir-deprecated
2. Comment out `fs: 'empty'` in the `next.config.js` since fs is not in use and causing a crash
3. Install `prop-types` as a dependency so it can be used within `head.js`

Making these changes allowed to the build complete and accessibility violations were then shown in the console as intended.

**Comment by Zidious** [comment]
Hey @pdavies88,

My apologies for the delay - is this issue still apparent on our `@latest` version? 


Please let me know.

**Comment by michael-siek** [comment]
closing please reopen if relevant
