### ISSUE TITLE
Webdriverio tests do not run in Node 16+

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#664]
Not only do they not run, they exit without any error message. Was stuck for a bit trying to figure out why it wouldn't start the tests. Was using Node 16, fix was to drop down to Node 14.

![image](https://user-images.githubusercontent.com/2433219/217952088-da341c63-ba39-4815-9f4c-2f4c61bcccdb.png)

**Comment by Zidious** [comment]
Closing - no longer a issue
