### ISSUE TITLE
Distribute `@axe-core/playwright` for both CJS and ESM

### ISSUE THREAD

**Issue by akornmeier** [dequelabs/axe-core-npm#670]
**Product:** `axe-core/playwright`

**Expectation:** Package distributes both CJS and ES modules

**Actual:** Package only distributed CJS module which causes a few issue when imported to a project using ES modules by default (like ViteJS referenced in issue #601). 

**Motivation:** ESM has been an out-of-box feature in Node since v14. Supporting projects that use that technology helps keeping the web accessible by using these great packages. 

<pre><code>
axe-core version: v4.6.3
@axe-core/playwright: v4.6.0

- Node version: v16.14.2
- Platform:  Mac
</code></pre>

**Comment by Zidious** [comment]
Hey Tony ☕ ,

This should be resolved in the `@latest` version. 

Please let me know if you run into any issues!

**Comment by michael-siek** [comment]
Closing please reopen if relevant. 

Also Hi @akornmeier! 🥂

**Comment by padmavemulapati** [comment]
Verified during 4.7.2 rlease testing and now @axe-core/playwright is supporting both CJS and ESM
