### ISSUE TITLE
Axe core cli not working on cpanel but working fine on root users

### ISSUE THREAD

**Issue by skynettechdeveloper** [dequelabs/axe-core-npm#676]
I have integrate it on our server and it work fine with the root user but when i m trying to access it through the cpanel its not working 
and giving us below error 
<pre><code>
/opt/cpanel/ea-nodejs16/bin/node /opt/cpanel/ea-nodejs16/bin/axe --chromedriver-path /bin/google-chrome --chrome-options no-sandbox https://google.com --verbose --show-errors

Running axe-core 4.6.3 in chrome-headless
Error: WebDriverError: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/opt/cpanel/ea-nodejs16/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/opt/cpanel/ea-nodejs16/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/opt/cpanel/ea-nodejs16/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  remoteStacktrace: '#0 0x555aa37f4303 <unknown>\n' +
    '#1 0x555aa35c8d37 <unknown>\n' +
    '#2 0x555aa35f1157 <unknown>\n' +
    '#3 0x555aa35ed330 <unknown>\n' +
    '#4 0x555aa362e4a6 <unknown>\n' +
    '#5 0x555aa3625753 <unknown>\n' +
    '#6 0x555aa35f8a14 <unknown>\n' +
    '#7 0x555aa35f9b7e <unknown>\n' +
    '#8 0x555aa384332e <unknown>\n' +
    '#9 0x555aa3846c0e <unknown>\n' +
    '#10 0x555aa3829610 <unknown>\n' +
    '#11 0x555aa3847c23 <unknown>\n' +
    '#12 0x555aa381b545 <unknown>\n' +
    '#13 0x555aa38686a8 <unknown>\n' +
    '#14 0x555aa3868836 <unknown>\n' +
    '#15 0x555aa3883d13 <unknown>\n' +
    '#16 0x2b24ae1c1ea5 start_thread\n'
}
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/
</code></pre>

Product: cli

Expectation: We we are trying to implement it on our cpanel( sub user) it not working properly but when i m accessing it through root whm it work properly

Actual: Resolve this issues

Motivation: to execute it in other panel as well

<pre><code>
axe-core version:4.6.0
@axe-core/[integration]: X.Y.Z

- Node version: 16.19.1
- Platform: Linux(centos)
</code></pre>

I tried almost all the options which are provided but it didnt work

it will be really helpful if anyone provide us some solution

**Comment by skynettechdeveloper** [comment]
Anyone out there to help?

**Comment by straker** [comment]
Thanks for the issue. Since you can run Chrome while logged in as admin but not a regular user, then it would appear to be a user permissions issue rather than a CLI issue. You could try adding `--disable-dev-shm-usage` to the chromeOptions and see if that helps.

**Comment by straker** [comment]
Closing due to lack of a response. Feel free to raise a new issue if you are able to provide further details.
