### ISSUE TITLE
cli: Server terminated early with status 127

### ISSUE THREAD

**Issue by BitwiseAndrea** [dequelabs/axe-core-npm#688]
Product:  cli

Expectation: Runs in a github action

Actual: Fails
Would like to use it

<code>
Running axe-core 4.3.3 in chrome-headless
Error: Error: Server terminated early with status 127
    at /actions-runner/_work/_tool/node/16.15.0/x64/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/remote/index.js:248:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/
</code>

<pre><code>
    - name: Run the application
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: npm run dev & npx wait-on http://localhost:3000

    - name: Run axe
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        npm install -g @axe-core/cli
        axe http://localhost:3000 --exit
</code></pre>

**Comment by michael-siek** [comment]
Hey @BitwiseAndrea do you by chance have xvfb/chromedrivers setup in your github actions?

**Comment by straker** [comment]
Closing due to lack of a response. Feel free to raise a new issue if you are able to provide further details.
