### ISSUE TITLE
remove `@wdio/sync`

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#695]
Since `@wdio/sync` no longer works with node 14 and with node 14 being EOL at the end of April we need to also drop support for `@wdio/sync` in our `@axe-devtools/webdriverio` package. We need to also make sure that we run test in CI to support node 18 with the `@axe-devtools/webdriverio` package.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core/webdriverio_4.7.1-alpha.383 , with WDIO version 8.6.7 - `.js` tests and APIs are working fine . Need to validate with `.mjs` 

<img width="724" alt="image" src="https://user-images.githubusercontent.com/47409579/235587286-0c34df8a-9fc3-41b2-9ba9-2af3f571cc18.png">
