### ISSUE TITLE
-bash: axe: command not found

### ISSUE THREAD

**Issue by kamal2222ahmed** [dequelabs/axe-core-npm#697]
Product: axe

Expectation: axe <URL> should give me results

Actual: should run a11y scan against a site

Motivation: need to use axe in CI/CD Pipeline

<pre><code>
axe-core version: latest
@axe-core/cli: latest

- Node version: v18.12.0  
- Platform:  Mac 
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Could you provide some more details about how you are trying to call the command, which CI/CD Pipeline you are using, and what the error message is that prevents the command from working?

**Comment by michael-siek** [comment]
Closing please reopen if relevant
