### ISSUE TITLE
axe-core-npm packages holding axe-core version 4.6.1 instead latest 4.6.3

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#699]
Steps to reproduce:
1. As part of release testing [RC](https://github.com/dequelabs/axe-core-npm/pull/691), all the packages , 
WEBDRIVERIO
WEBDRIVERJS
PUPPETEER
PLAYWRIGHT
CLI
REACT
all holding axe-core 4.6.1 .
Expected:
As axe-core 4.6.3 is the latest and expected version 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/47409579/227229084-1ef62f3f-90e3-4a14-a20d-09d1c197b1c7.png">

**Comment by straker** [comment]
Axe-core is currently on 4.7.2
