### ISSUE TITLE
cli: force chrome bin path

### ISSUE THREAD

**Issue by sinedied** [dequelabs/axe-core-npm#700]
Product: cli 

Expectation: 
I'm embedding the CLI in another NPM package pre-configured to work out of the box for our needs. In that context, I would like to install a working Chrome / Chromedriver combo to make sure it works on the target machine, so I would like to be able to force chromedriver and chrome binary paths to be used.

Actual: There's currently an option to force chromedriver path, but not to force chrome binary path.

Motivation: Add an option (or environment variable) so we can force the chrome path to be used.

<pre><code>
@axe-core/cli: 4.6.0

- Node version: XX  v18.14.2
- Platform:  Mac
</code></pre>

**Comment by straker** [comment]
Closed via #704
