### ISSUE TITLE
ESM support throwing error for dynamic import

### ISSUE THREAD

**Issue by robhicks** [dequelabs/axe-core-npm#719]
Product: react

Expectation:  await import('@axe-core/react') should work

Actual: cannot find @axe-core/react

Motivation: It is unusable

<pre><code>
axe-core version: 4.7.0
@axe-core/react: 4.7.0

- Node version: 18.12.1
- Platform:  Linux
</code></pre>

**Comment by Zidious** [comment]
Hey @robhicks,

We are aware of some import issues for ESM support in some of out packages. 

We are looking into and will cut a 4.7.1 release shortly
