### ISSUE TITLE
@axe-core/react fail to build on Vite after 4.7.0

### ISSUE THREAD

**Issue by adrifer** [dequelabs/axe-core-npm#721]
Product: @axe-core/react

Expectation: When including @axe-core/react 4.7.0 on a Vite/React/TS repo should build

Actual: after updating to @axe-core/react on a Vite/React/TS repo now when building I get:
[commonjs--resolver] Failed to resolve entry for package "@axe-core/react". The package may have incorrect main/module/exports specified in its package.json.

This doesn't happen with 4.6.2 version.

In case you want it, this a repro (basic Vite/React/TS project with @axe-core/react installed):  https://stackblitz.com/edit/vitejs-vite-clopnm?file=package.json
Running `npm install` and then `npm run build`, it should repro it. 

<pre><code>
@axe-core/react: 4.7.0

- Node version: v16.13.1, but I tested with other like 14 
- Platform:  Windows
</code></pre>

Let me know if you need anything else from my side.

Thanks!

**Comment by Zidious** [comment]
Hey @adrifer ,

We are aware of some import issues for ESM support in some of our packages. 

We are looking into and will cut a 4.7.1 release shortly

**Comment by adrifer** [comment]
Awesome! 
I'm not blocked on anything with this, as I can target 4.6.2 for now. But I didn't see the issue so I wanted to let you know!

Thanks for the work!
