### ISSUE TITLE
axe-core/react cannot be resolved

### ISSUE THREAD

**Issue by qidydl** [dequelabs/axe-core-npm#725]
Product: react

Expectation: The module should be able to be loaded.

Actual: When trying to build, we receive the following error: `Module not found: Error: Can't resolve '@axe-core/react'`. This error did not occur with version 4.6.1.

Motivation: I want to be able to use the latest version of axe.

<pre><code>
axe-core version: not specified/latest
@axe-core/react: 4.7.0

- Node version: 18.16.0
- Platform: Windows
</code></pre>

**Comment by Zidious** [comment]
Hey @qidydl,

Apologies - there was a known issue with the imports of our React package, if you could try the `@next` version we should be releasing a stable 4.7.1 version soon

**Comment by lacazeto** [comment]
I was getting the same error with the version tagged with `next`, so I had to downgrade it to `4.6.1` to make it work!

**Comment by ckruppe** [comment]
I have the same problem too with the 4.7.0 its because the index.mjs is not existing but the exports field is pointing to it.
Upgrading to 4.7.1-alpha.385 fixes the issue for me.

**Comment by abencun-symphony** [comment]
Same for me, 4.7.1-alpha.385 fixes this issue. Looks like the files in package are all messed up in 4.7.0, files are missing in the dist/ folder for me.

**Comment by abencun-symphony** [comment]
4.7.1 was released and resolved this for us.

**Comment by qidydl** [comment]
It does look like 4.7.1 resolved the issue, thanks!
