### ISSUE TITLE
Issues with the latest update

### ISSUE THREAD

**Issue by pradnyakambli1984** [dequelabs/axe-core-npm#728]
Hello,

We are using axe-core/react package in our code base and the latest update is creating code compilation issues.
On further debugging observed that the following code in the package.json of this package is a problem -

  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
  },

The paths should be prefixed as "dist/" instead of "./dist/".
<pre><code>
axe-core version: "^4.5.2"
@axe-core/react: "^4.5.2"

- Node version: 18
- Platform:  Windows
</code></pre>

**Comment by abencun-symphony** [comment]
For us 4.7.1 resolved this.
