### ISSUE TITLE
Webdriverjs hangs when page has lazy loaded iframe

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#744]
Similar to #727, webdriverjs has a similar issue when encountering a lazy loaded iframe. However instead of failing when selecting the iframe, it instead hangs on the `switchTo().frame` call and won't release until the `pageLoad` selenium timeout. There's also another issue in that `switchTo().frame` timing out puts the driver into a bad state so when we try to process the results we try to call `executeScript` and that hangs until the `script` selenium timeout before the code finally gives an error message.

Note that this only happens when using chromedriver. Using gekodriver doesn't have this issue.

**Comment by padmavemulapati** [comment]
Valdiated with the latest build - 4.7.3-alpha.398

testfile
```
const AxeBuilder = require('@axe-core/webdriverjs');
const WebDriver = require('selenium-webdriver');
const fs = require('fs');

const driver = new WebDriver.Builder().forBrowser('chrome').build();

driver.get('https://broken-workshop.dequelabs.com/').then(() => {
  new AxeBuilder(driver).analyze(function (err, results) {
    if (err) {
      // Handle error somehow
    }
    fs.writeFile("./Analyse472.json", JSON.stringify(results, null,4),(err)=>
    {if(err){
        console.error(err);
        return;
        };
        console.log("File has been created");
    })
  });
});
```
also tried test page: `https://www.rastoder.si/`

this same test worked well for `4.7.2` version and now getting below error:

```
/Users/dq_user/Downloads/axe-core-integrations/axe-core-npm-integrations/webdriverjs/test.js:9
  new AxeBuilder(driver)
  ^

TypeError: AxeBuilder is not a constructor
    at /Users/dq_user/Downloads/axe-core-integrations/axe-core-npm-integrations/webdriverjs/test.js:9:3
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```

Note: Build 4.7.3-alpha.398 is working fine for `.mjs` test.

**Comment by padmavemulapati** [comment]
Verified the fix, updated the changes to the test file,
testfile now looks like:
```
const { AxeBuilder } = require('@axe-core/webdriverjs');
const WebDriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const fs = require('fs');
const driver = new WebDriver.Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().headless()).build();

driver.get('https://www.rastoder.si/').then(() => {
  new AxeBuilder(driver) .analyze(function (err, results) {
    if (err) {
      // Handle error somehow
    }
    fs.writeFile("./lazyloadpage.json", JSON.stringify(results, null,4),(err)=>
    {if(err){
        console.error(err);
        return;
        };
        console.log("File has been created");
    })
  });
});
```
Got the results in "lazyloadpage.json" 

  ## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _@axe-core/webdriverjs_ |
| **Version**           | _4.7.3-alpha.398_ |
| **selenium-webdriver version**      | _24.10.0_ |
|**Chromedriver Version** |_114.0.1_|
