### ISSUE TITLE
`@axe-core/puppeteer` does not run correctly when using jest/mocha 

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#76]
when using jest/mocha https://github.com/dequelabs/axe-core-npm/blob/develop/packages/puppeteer/src/axePuppeteer.ts#L31 frame _could_ be null we should do something like 
```js
if (frame !== null) {
...
}
```

**Comment by padmavemulapati** [comment]
- using mocha -  axe-core/puppeteer running succesfully.
![image](https://user-images.githubusercontent.com/47409579/95090351-cb00df00-0742-11eb-923e-db638b1ddb29.png)

**Comment by jeeyyy** [comment]
No docs necessary
