### ISSUE TITLE
Error occurs when WebdriverIO version is higher than 5

### ISSUE THREAD

**Issue by abakarovmaks** [dequelabs/axe-core-npm#798]
### Product

webdriverio

### Product Version

4.7.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
The test must pass succesfully.

#### Actual
Test fails due to error "An instantiated WebdriverIO client greater than v5 is required"

#### How to Reproduce
```
import { browser } from '@wdio/globals';
import AxeBuilder from '@axe-core/webdriverio';

async function checkAxeAccesability() {
  const builder = new AxeBuilder({ client: browser });
  const result = await builder.analyze();
  const violations = result.violations.filter(
    (violation) => violation.impact === 'critical'
  );
  const errorMessages = violations.map((violation, index) => {
    return `${index + 1}. ${violation.help}`;
  });
  const error = errorMessages.join('\n');
  assert.strictEqual(violations.length, 0, error);
}

await checkAxeAccesability();
```

#### Additional context
I trying to run the test in WebdriverIO.
My dependencies: 
```
    "@axe-core/webdriverio": "^4.7.3",
    "axe-core": "^4.7.2",
```
My WebdriverIO version is 8.14.6, Chromedriver version is  116.0.5845.96
When I run the test I get an error "An instantiated WebdriverIO client greater than v5 is required". (but my version of WebdriverIO is 8.14.6).
But when I remove some code from the file index.js which is in the folder node_modules/@axe-core/webdriverio/dist everything works fine.
Removed code from index.js:
```
  (0, import_assert2.default)(
      isWebdriverClient(client),
      "An instantiated WebdriverIO client greater than v5 is required"
    );
```
and
```
var isWebdriverClient = (client) => {
  if (!client || typeof client !== "object") {
    return false;
  }
  if (typeof client.execute !== "function") {
    return false;
  }
  if (typeof client.switchToFrame !== "function") {
    return false;
  }
  return true;
};
```
Is it the global issue with new version of WebdriverIO or what?

Thank you in advance for understanding.
Best regards.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core/webdriverio - 4.7.4-acf6b0f.0

Able to see chromedriver - 116 version and test ran successfully
Steps followed:
1. npm init -y
2. npm install @axe-core/webdriverio@next (4.7.4-acf6b0f.0)
3. npm install webdriverio(8.16.4)
4. npm install chromedriver(116.0.0)
5. added test.js
```
const { AxeBuilder } = require('@axe-core/webdriverio');
const { remote } = require('webdriverio');

(async () => {
  const client = await remote({
    logLevel: 'error',
    capabilities: {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['headless', 'disable-gpu']
      }
    }
  });
  await client.url('https://dequeuniversity.com/demo/mars/');

  try {
    const results = await new AxeBuilder({ client }).analyze();
    console.log(results);
  } catch (e) {
    // do something with the error
  }

  client.deleteSession();
})();
```
6. Run with `node test.js` 



![Image](https://github.com/dequelabs/axe-core-npm/assets/47409579/f24c9d3d-0cdc-4c53-9de0-3517d5b08399)


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.7.4-acf6b0f.0_ |
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 116.0.5845.110 (Official Build) (64-bit)_| (edited)

**Comment by straker** [comment]
QA Notes: need to setup a project using the [wdio setup guide](https://webdriver.io/docs/gettingstarted#install-cli-manually) to create a project. When running the config select `e2e` tests as the setup to ensure you get the `local` runner (not the browser-runner). Allow it to create sample code for you. In one of the sample files you can import `browser` from `@wdio/globals` and then pass that to `AxeBuilder`

**Comment by padmavemulapati** [comment]
using `@wdio/globals` still seeing the error:

Steps reproduced:
Follow the [wdio set up](https://webdriver.io/docs/gettingstarted/#install-cli-manually), in one of the `spec.js` file implemented the code to use `axeBuilder` and `@wdio/globals` 

test/pageobjects/login.page.js

```
import { browser } from '@wdio/globals';
import AxeBuilder from '@axe-core/webdriverio';
import assert from 'assert'; // Import the assert module if not already imported

describe('Accessibility Check', () => {
  it('should check accessibility using Axe-Core', async () => {
    async function checkAxeAccessibility() {
      const builder = new AxeBuilder({ client: browser });
      const result = await builder.analyze();
      const violations = result.violations.filter(
        (violation) => violation.impact === 'critical'
      );
      const errorMessages = violations.map((violation, index) => {
        return `${index + 1}. ${violation.help}`;
      });
      const error = errorMessages.join('\n');
      assert.strictEqual(violations.length, 0, error);
    }

    await checkAxeAccessibility();
  });
});
```

passed the path of spec file in `wdio.conf.js`

```
specs: [
    './test/pageobjects/test.page.js' // Path to your test spec file
  ],
```
(Tried with test.spec.js too)

Run the test using `npm run wdio`

getting the similar error saying "An instantiated WebdriverIO client greater than V5 required"

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/37f6506e-f3be-4753-9129-5035d1cd4651)


even though we have "@wdio/globals-v8.24.2" and "@axe-core/webdriverio-v4.8.1"


![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/8452c57d-7c44-4828-a309-8ca43cdb2f5e)


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.8.1_ |
|**Package-Version**|_@wdio/globals-v8.24.2_|
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 119.0.6045.159 (Official Build) (64-bit)_| (edited)

**Comment by padmavemulapati** [comment]
@straker , reopened this ticket as this  error still seeing with `wdio/globals`

**Comment by straker** [comment]
@padmavemulapati this hasn't been released yet so using v4.8.1 won't have the fix in it. You'll need to test with current develop

**Comment by padmavemulapati** [comment]
@straker , with @next version it is working.

Steps validated:

1. wdio.conf.ts configured
```
 runner: 'local',
 specs: [
        './test/specs/**/*.ts'
    ],
 maxInstances: 10,
    capabilities: [{
        browserName: 'chrome'
    }],
baseUrl: 'https://the-internet.herokuapp.com/', 
```
etc.,

```test file
import { expect, browser, $ } from "@wdio/globals";
import AxeBuilder from "@axe-core/webdriverio";

describe("My Login application", () => {
  it("should login with valid credentials", async () => {
    await browser.url("/login");

    await $("#username").setValue("tomsmith");
    await $("#password").setValue("SuperSecretPassword!");
    await $('button[type="submit"]').click();

    const axe = new AxeBuilder({ client: browser });
    const results = await axe.analyze();

    console.log(results.violations);

    await expect($("#flash")).toBeExisting();
    await expect($("#flash")).toHaveTextContaining(
      "You logged into a secure area!"
    );
  });
});

```
working fine 
![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/c2c80f87-155d-4cfb-a9be-8cea8b7939ff)

and the results:

https://github.com/dequelabs/axe-core-npm/assets/47409579/de4d95f0-c6e2-4470-b7e3-1229301e5a18


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.8.2-aab6d3c.0_ |
|**Package-Version**|_@wdio/globals-v8.24.2_|
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 119.0.6045.159 (Official Build) (64-bit)_| (edited)

**Comment by padmavemulapati** [comment]
Verified with the canary version `axe-core/webdriverio_4.8.3-6b60442.0` and `@wdio/globals-8.24.2`

Steps validated:

1. wdio.conf.ts configured
```
 runner: 'local',
 specs: [
        './test/specs/**/*.ts'
    ],
 maxInstances: 10,
    capabilities: [{
        browserName: 'chrome'
    }],
baseUrl: 'https://the-internet.herokuapp.com/', 
```
etc.,

```test file
import { expect, browser, $ } from "@wdio/globals";
import AxeBuilder from "@axe-core/webdriverio";

describe("My Login application", () => {
  it("should login with valid credentials", async () => {
    await browser.url("/login");

    await $("#username").setValue("tomsmith");
    await $("#password").setValue("SuperSecretPassword!");
    await $('button[type="submit"]').click();

    const axe = new AxeBuilder({ client: browser });
    const results = await axe.analyze();

    console.log(results.violations);

    await expect($("#flash")).toBeExisting();
    await expect($("#flash")).toHaveTextContaining(
      "You logged into a secure area!"
    );
  });
});

```
working fine 



https://github.com/dequelabs/axe-core-npm/assets/47409579/2e264faa-bfa0-4712-bc12-638c7cd0dcd0




## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.8.3-6b60442.0_ |
|**Package-Version**|_@wdio/globals-v8.24.2_|
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129   & Firefox 121.0_| (edited)
