### ISSUE TITLE
Empty Img Alt as incomplete

### ISSUE THREAD

**Issue by NashiCodes** [dequelabs/axe-core-npm#813]
### Product

puppeteer

### Question

I'm building an API that uses AxePuppeteer to evaluate WP pages and posts, and im facing and issue, when the creator does not pass a alt-text in a image, it return as passed because it has an empty alt atributte.
is there any way to make return as incomplete ? since, as i read, axe can't say that it is a decorative img or not ?

test exemple: 

img tag:
`<img src=\"https://www.reliablesoft.net/wp-content/uploads/2019/06/brownies.jpg\" alt=\"\" srcset=\"\">`

```
response:
"nodes": [
    {
      "any": [
        {
          "id": "has-alt",
          "data": null,
          "relatedNodes": [],
          "impact": "critical",
          "message": "Element has an alt attribute"
        },
        {
          "id": "presentational-role",
          "data": { "role": "presentation" },
          "relatedNodes": [],
          "impact": "minor",
          "message": "Element's default semantics were overriden with role=\"presentation\""
        }
      ],
      "all": [],
      "none": [
        {
          "id": "alt-space-value",
          "data": null,
          "relatedNodes": [],
          "impact": "critical",
          "message": "Element has a valid alt attribute value"
        }
      ],
      "impact": null,
      "html": "<img src=\"https://www.reliablesoft.net/wp-content/uploads/2019/06/brownies.jpg\" alt=\"\" srcset=\"\">",
      "target": ["img[srcset=\"\"]"]
    }
  ]
```

**Comment by Zidious** [comment]
You may need to manually evaluate whether the images being used does not provide any information or they are described in the page content. An `img` tag with `alt=""` is a valid for marking the image as decorative, example:

```html
<img src="https://www.deque.com/wp-content/uploads/2022/10/deque-hero-accessible-experiences.svg" alt="" />
```

If you check the axe-results object after `analyze()` it should put the `image-alt` rule under `passes`. 



More information about [`image-alt`](https://dequeuniversity.com/rules/axe/4.7/image-alt?application=axeAPI).

**Comment by NashiCodes** [comment]
i'm using it on a governamental WP sites, so i cant manually evaluate all images.
because of it, i thougth i could mark all empty alt as incomplete, so that the content creators could evaluate their pages of their own...

**Comment by WilcoFiers** [comment]
@NashiCodes To do something like this would require a custom rule. This is something that we do not provide support for in our open source projects. There is broad support for custom rules in our axe DevTools product line though. If your organisation is a Deque customer please contact your Deque representative, or our helpdesk for more information. If you are not a Deque customer and are interested to learn more about what the features and benefits of axe DevTools you can find more info about it on [deque.com/axe/devtools/](https://www.deque.com/axe/devtools/).

**Comment by padmavemulapati** [comment]
as per Wilco, this can be done with custom-rule which is axe-devtools feature, said requirement not considering as bug and closing
