### ISSUE TITLE
axe-core-npm v4.8.0 - QA Needed

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#848]
axe-core-npm v4.8.0 QA Needed

Release Candidate: https://github.com/dequelabs/axe-core-npm/pull/846

**Comment by padmavemulapati** [comment]
Blocked with [the issue on react]( https://github.com/dequelabs/axe-core-npm/issues/858)

**Comment by padmavemulapati** [comment]
Regression completed.

Observations:

Three issues were raised during regression, of which two issues closed( https://github.com/dequelabs/axe-core-npm/issues/858 & https://github.com/dequelabs/axe-core-npm/issues/852) and another low-priority issue is still open (https://github.com/dequelabs/axe-core-npm/issues/857), but not a blocker for the release on build - v4.7.4-62fd241.0  

We are good to go with the Build- `axe-core-npm_4.7.4-62fd241.0`

Please find [Testrail- testplan ](https://dequeqa.testrail.io/index.php?/plans/view/2252). 
For access details, please refer mail communication given for sign-off

**Comment by davereid** [comment]
FYI we are still seeing https://github.com/dequelabs/axe-core-npm/issues/852 even with the 4.8.0 release.
