### ISSUE TITLE
Update prepare_release.sh

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#850]
This is a template ticket that will need to be copied into each repository. 

There should be a release candidate shell script in each repo that does, at minimum, the following:

1. Generates the new version number and updates files
  - If the repo is version locked to axe-core, the shell script should take as an optional unnamed argument the semver to use `sh release-script.sh patch`. E.g. if using `standard-version` the shell script should run it with the `--release-as` flag passing the unnamed argument `npx standard-version --release-as patch`. This allows us to release `feat` commits as a patch.

2. Generates changelog file

If the current shell script does not exist or does not do the above, it needs to be modified to doso. Depending on repo, there may be additional functionality in the existing shell script which should remain as-is

**Comment by padmavemulapati** [comment]
@Zidious , is this QA-Required?

**Comment by Zidious** [comment]
Nope no QA required
