### ISSUE TITLE
BUG: CLI-getting "axe: command not found " even after successfully installed CLI

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#852]
### Product

cli

### Product Version

4.7.4-f03670b.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
After @axe-core/cli installed successfully, `axe --help`  or `axe with url` should give respective output

#### Actual
```
MacBook-Pro:cli dq_user$ axe --version
bash: axe: command not found
MacBook-Pro:cli dq_user$ axe --help
bash: axe: command not found
```

#### How to Reproduce
1. Created a Directory and created a package.json using `npm init -y`
2. Insalled axe-core/cli canary version ('npm install @axe-core/cli@next) (Installed gobally using `-g` and locally both)
3. Tried to run the command `axe --version` to make sure correct canary is installed

Issue: its giving 

```
MacBook-Pro:cli dq_user$ axe --version
bash: axe: command not found
MacBook-Pro:cli dq_user$ axe --help
bash: axe: command not found
```
#### Additional context
Tried in Windows and MAC both , issue is there on both OS

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm_|
|**Version** | _4.7.4-f03670b.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|

**Comment by padmavemulapati** [comment]
Verified with the latest fix, now not getting `axe` not found error.

<img width="945" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/abf3e683-a11b-4774-b199-fc05a3a51dc5">

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|

**Comment by davereid** [comment]
We are still seeing this bug with the recent 4.8.0 release as of three hours ago. Do we need another release with this fix?

**Comment by davereid** [comment]
You can see on https://www.npmjs.com/package/@axe-core/cli?activeTab=code that the dist directory is still missing. I think this issue needs to be re-opened.

**Comment by davereid** [comment]
I can also validate that https://registry.npmjs.org/@axe-core/cli/-/cli-4.8.0.tgz is missing the `dist` directory from the contents of the tarball.

**Comment by dbjorge** [comment]
Just confirming that we agree this affects 4.8.0 - we've begun a new release process for a v4.8.1 which will contain the fix for this, and we'll be investigating how to avoid this mismatch of which version gets QA tested vs released to prevent issues from accidentally escaping to production like this in the future.

**Comment by dbjorge** [comment]
Clarification for QA: the fix for this *is* already merged in #851, which would normally mean we'd have closed this issue. I'm leaving it open for the purposes of users being able to track the outage in the published version. We can close this once we've verified that `npx @axe-core/cli@4.8.1 --help` is available and working.

**Comment by padmavemulapati** [comment]
We have a similar [ticket for windows](https://github.com/dequelabs/axe-core-npm/issues/868) , but when we set the PATH in `environment variables` it is working as expected. As @dbjorge said, once we have verified the `patch release 4.8.1`we can close this .

**Comment by dbjorge** [comment]
4.8.1 has been released. Verified that it fixes the issue:

```sh
> npx -y @axe-core/cli@4.8.1 --version
4.8.1 
```
