### ISSUE TITLE
ChromeDriver only supports Chrome version 113

### ISSUE THREAD

**Issue by vkochhar-dev** [dequelabs/axe-core-npm#859]
Error: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 117.0.5938.132 with binary path /usr/bin/google-chrome
    at Object.throwDecodedError (/opt/hostedtoolcache/node/20.8.0/x64/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/opt/hostedtoolcache/node/20.8.0/x64/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/opt/hostedtoolcache/node/20.8.0/x64/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: '#0 0x560013e10133 <unknown>\n' +
    '#1 0x560013b44966 <unknown>\n' +
    '#2 0x560013b725ec <unknown>\n' +
    '#3 0x560013b6d8da <unknown>\n' +
    '#4 0x560013b6a07b <unknown>\n' +
    '#5 0x560013ba99ad <unknown>\n' +
    '#6 0x560013ba918f <unknown>\n' +
    '#7 0x560013ba09a3 <unknown>\n' +
    '#8 0x560013b7546a <unknown>\n' +
    '#9 0x560013b7655e <unknown>\n' +
    '#10 0x560013dcfcae <unknown>\n' +
    '#11 0x560013dd38fe <unknown>\n' +
    '#[12](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:13) 0x5600[13](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:14)ddcf20 <unknown>\n' +
    '#13 0x560013dd4923 <unknown>\n' +
    '#[14](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:15) 0x560013da7c0e <unknown>\n' +
    '#[15](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:16) 0x560013df7b08 <unknown>\n' +
    '#[16](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:17) 0x560013df7c97 <unknown>\n' +
    '#[17](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:18) 0x560013e08113 <unknown>\n' +
    '#[18](https://github.com/KPMG-UK/gcp-project-vertex-ai-chat-demo/actions/runs/6434274936/job/17473134498#step:6:19) 0x7f9899094b43 <unknown>\n'
}
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

Error: Process completed with exit code 1.

**Comment by straker** [comment]
Thanks for the issue. Does installing the matching `chromedriver` resolve the issue? More info can be found here https://github.com/dequelabs/axe-core-npm/issues/816

**Comment by padmavemulapati** [comment]
Whenever this chromedriver issue comes, we used to update the chromedriver globally using 
`npm install chromedriver --update -g` so that it updates the compatible chromedriver and works fine. 
@straker , can you confirm this solution too, along with the solution provided in [#816](https://github.com/dequelabs/axe-core-npm/issues/816)

**Comment by padmavemulapati** [comment]
Verified with the latest version of @axe-core/cli_4.7.4-62fd241.0` , chromedriver when ever version compatibility error showing, we can have a solution uisng `--chromedriver-path` option.

Steps to validate:

1) To get a updated chromedriver version at the global location
     `npm install chromedriver --update -g`

2) To Find out where chromedriver is  we can use a command at the terminal in MAC -  `which chromedriver` and in windows - `Where chromedriver`

     Which gives you something like this
     `/usr/local/bin/chromedriver` _From a mac_

3) Run axe cli with the following flag. _Based on above step_
     Flag: `--chromedriver-path /usr/local/bin/chromedriver`
     
**Example:**   

```bash
axe  --chromedriver-path /usr/local/bin/chromedriver  https://google.com
```

### Getting more comfortable

```bash
axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://google.com
```

We can see the output successfully, even we have non-compatible version saved in our machine and trying to run `axe-cli` . This above process will update the compatibility version of chromdriver and pick the path from where the compatible version of chromedriver located and working as expected.

Output:

```
axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://google.com
Running axe-core 4.8.2 in chrome-headless

Testing http://google.com ... please wait, this may take a minute.

  Violation of "aria-allowed-role" with 1 occurrences!
    Ensures role attribute has an appropriate value for the element. Correct invalid elements at:
     - #APjFqb
    For details, see: https://dequeuniversity.com/rules/axe/4.8/aria-allowed-role

  Violation of "aria-valid-attr-value" with 2 occurrences!
    Ensures all ARIA attributes have valid values. Correct invalid elements at:
     - #APjFqb
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.8/aria-valid-attr-value

  Violation of "color-contrast" with 8 occurrences!
    Ensures the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds. Correct invalid elements at:
     - .uU7dJb
     - a[data-usg="AOvVaw33zjaJZ_ogw8iPEm4kPGYh"]
     - a[data-usg="AOvVaw3Oj62V1xNd5oAI6Vxou5Lx"]
     - a[data-usg="AOvVaw2SJ4zwRVXKyZr53qG9dm4K"]
     - .pHiOh:nth-child(4)
     - a[data-usg="AOvVaw2y-DJehqHRQuhUzwsARmol"]
     - a[data-usg="AOvVaw25sheD5OGrPUyBw_FdCQOy"]
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.8/color-contrast

  Violation of "region" with 8 occurrences!
    Ensures all page content is contained by landmarks. Correct invalid elements at:
     - .gb_yd > div:nth-child(1)
     - .gb_za
     - .lnXdpd
     - #SIvCob
     - .uU7dJb
     - .AghGtd
     - a[data-usg="AOvVaw2y-DJehqHRQuhUzwsARmol"]
     - a[data-usg="AOvVaw25sheD5OGrPUyBw_FdCQOy"]
    For details, see: https://dequeuniversity.com/rules/axe/4.8/region

19 Accessibility issues detected.
Testing complete of 1 pages

Please note that only 20% to 50% of all accessibility issues can automatically be detected. 
Manual testing is always required. For more information see:
https://dequeuniversity.com/curriculum/courses/testingmethods
```

### Screenshot:
<img width="951" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/d7b2c767-40bc-4657-9312-ea3869f9a30b">

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm/react_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
