### ISSUE TITLE
Repo should have an issue template

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#90]
With multiple packages we should have an issue template that helps us track issues for each of the packages better. Right now I can open up a ticket but there's no "good" way to know which package its against (unless the user puts that in the title for us).

**Comment by padmavemulapati** [comment]
Verified in the latest `axe-core-npm` - realised a doc change - updated the "ISSUE_TEMPLATE.MD" file
![image](https://user-images.githubusercontent.com/47409579/118499144-48161d00-b744-11eb-8aee-54283b40450b.png)

**Comment by michael-siek** [comment]
Closing no docs required
