### ISSUE TITLE
CI: Replace update-axe-core workflow with updated workflow from axe-api-team/public

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-npm#902]
https://github.com/dequelabs/axe-core-npm/blob/develop/.github/workflows/update-axe-core.yml Should be replaced with https://github.com/dequelabs/axe-api-team-public/tree/main/.github/actions/create-update-axe-core-pull-request-v1 this will resolve dependabot trying to update https://github.com/dequelabs/axe-core-npm/pull/889

**Comment by michael-siek** [comment]
closed as completed I apologize I referenced the wrong ticket number 
https://github.com/dequelabs/axe-core-npm/pull/910
