### ISSUE TITLE
Require QA consideration in PRs

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#937]
Set up https://github.com/dequelabs/axe-api-team-public/blob/main/.github/actions/semantic-pr-footer-v1 so it will block a PR that does not have at least one of the following:

- There is a link to a valid issue in the description of the PR
- The words "QA NOTES" appear in the description of the PR
- The words "QA NOT NEEDED" appear in the description of the PR

**Comment by padmavemulapati** [comment]
Verified the Github actions, workflow defined for the action for QA-required actions and can find the link below:

https://github.com/dequelabs/axe-core-npm/blob/38e440c24627b4f7316f9d04a1e05803a2c5d5d6/.github/workflows/semantic-pr-footer.yml#L15

## Screenshot:
<img width="1272" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/e027a5e5-391b-4f71-8603-a33d0fb10854">
