### ISSUE TITLE
webdriverjs 4.7.3 broke default export in CJS

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#948]
In v4.7.3 we released webdriverjs with a breaking change where we broke the default export and changed it to a `.default` export (in CJS). We need to fix this and go back to the default export, but since this is now released we also need to support the `.default` export so we don't break anyone using v4.7.3. 

QA NOTES: We'll be supporting both default and `.default` exports in all our packages going forward, and some packages will also have a named export. Tests will need to be set up in both ESM and commonJS format to import / require (respectively) the default export and possibly named export, and in CJS require the `.default` export.

**Comment by padmavemulapati** [comment]
Verified with the latest canary build (axe-core-npm_4.8.3-6b60442.0)

<details> <summary> 1. CJS  </summary>

1.  Implicit Export   -  Const implicitDefaultExport = require(‘@axe-core/webdriverjs’);  - 
  test snippet:
```
await driver.get('http://abcdcomputech.dequecloud.com/');
   const results = await new implicitExport(driver).analyze();
```

2. Explicit Export   -  Const explicitDefaultExport = require(‘@axe-core/webdriverjs’).default;

testSnippet:
```
await driver.get('http://abcdcomputech.dequecloud.com/');
   const results = await new explicitExport(driver).analyze();
```

3. Named Export  - Const { AxeBuilder } = require(‘@axe-core/webdriverjs’); (or)Const  AxeBuilder = require(‘@axe-core/webdriverjs’).AxeBuilder;

test snippet:

```
await driver.get('http://abcdcomputech.dequecloud.com/');
 const results = await new AxeBuilder(driver).analyze();
```


</details>


<details> <summary>  2. MJS </summary>

1.  Implicit Export   -  import  AxeBuilder  from '@axe-core/webdriverjs';  - 
  test snippet:
```
await driver.get('http://abcdcomputech.dequecloud.com/');
   const results = await new implicitExport(driver).analyze();
```

2. Named Export  - import  { AxeBuilder } from '@axe-core/webdriverjs'; 

test snippet:

```
await driver.get('http://abcdcomputech.dequecloud.com/');
 const results = await new AxeBuilder(driver).analyze();
```


</details>


<details> <summary> 3. TS </summary>

1.  Implicit Export   -  import  AxeBuilder  from '@axe-core/webdriverjs';  - 
  test snippet:
```
await driver.get('http://abcdcomputech.dequecloud.com/');
   const results = await new implicitExport(driver).analyze();
```

2. Named Export  - import  { AxeBuilder } from '@axe-core/webdriverjs'; 

test snippet:

```
await driver.get('http://abcdcomputech.dequecloud.com/');
 const results = await new AxeBuilder(driver).analyze();
```

</details>

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.8.3-6b60442.0_ |
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129   & Firefox 121.0_| (edited)
