### ISSUE TITLE
puppeteer: Using `withTags` vs `options` with rule id do not yield the same results

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#99]
This is still an issue. 
more context: https://github.com/dequelabs/axe-puppeteer/issues/55

**Comment by AdnoC** [comment]
Going to the specified page and manually running axe-core produces no violations. Could this be an axe-core issue?

**Comment by AdnoC** [comment]
The specified page is rotating content by `-7.016727638069627e-14` degrees, which when axe-core computes is rounded to 0. Since we detect the page isn't rotating, we don't fail the css-orientation-lock rule. Not an axe-core issue but a test-page issue.

**Comment by jeeyyy** [comment]
Looking through the test cases in act, it seems like this example was to demonstrate the rotation of an arbitrary degree.

Asides unlike mentioned in original issue, the withTags and options work as expected now. Closing.
